### ISSUE TITLE
Tensorboard error for the quick-start example

### ISSUE THREAD

**Issue by vakker** [polyaxon/polyaxon#666] opened 2020-01-21 17:10 UTC
### Describe the bug
I'm running the examples from the `quick-start` guide and when I tried to start Tensorboard I got the error:
```
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 316, in create_or_update_deployment return self.create_deployment(name=name, body=body), True File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 302, in create_deployment namespace=self.namespace, body=body File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 175, in create_namespaced_deployment (data) = self.create_namespaced_deployment_with_http_info(namespace, body, **kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 266, in create_namespaced_deployment_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 266, in POST body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 21 Jan 2020 17:03:28 GMT', 'Content-Length': '374'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions is forbidden: User \"system:serviceaccount:polyaxon:polyaxon-polyaxon-serviceaccount\" cannot create resource \"deployments\" in API group \"extensions\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"group":"extensions","kind":"deployments"},"code":403} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 319, in create_or_update_deployment return self.update_deployment(name=name, body=body), False File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 309, in update_deployment name=name, namespace=self.namespace, body=body File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 4089, in patch_namespaced_deployment (data) = self.patch_namespaced_deployment_with_http_info(name, namespace, body, **kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 4189, in patch_namespaced_deployment_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 393, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 21 Jan 2020 17:03:28 GMT', 'Content-Length': '484'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions \"plx-tensorboard-5aa275f671f64a75924c66323cb0e6a4\" is forbidden: User \"system:serviceaccount:polyaxon:polyaxon-polyaxon-serviceaccount\" cannot patch resource \"deployments\" in API group \"extensions\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"name":"plx-tensorboard-5aa275f671f64a75924c66323cb0e6a4","group":"extensions","kind":"deployments"},"code":403} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/polyaxon/polyaxon/scheduler/tensorboard_scheduler.py", line 53, in start_tensorboard reconcile_url=get_tensorboard_reconcile_url(tensorboard.unique_name)) File "/polyaxon/polyaxon/polypod/tensorboard.py", line 234, in start_tensorboard reraise=True) File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 322, in create_or_update_deployment raise PolyaxonK8SError(e) polyaxon_k8s.exceptions.PolyaxonK8SError: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 21 Jan 2020 17:03:28 GMT', 'Content-Length': '484'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions \"plx-tensorboard-5aa275f671f64a75924c66323cb0e6a4\" is forbidden: User \"system:serviceaccount:polyaxon:polyaxon-polyaxon-serviceaccount\" cannot patch resource \"deployments\" in API group \"extensions\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"name":"plx-tensorboard-5aa275f671f64a75924c66323cb0e6a4","group":"extensions","kind":"deployments"},"code":403} 
```

### To Reproduce
```
$ git clone https://github.com/polyaxon/polyaxon-quick-start.git
$ # run create, init, etc.
$ polyaxon run -f polyaxonfile_hyperparams.yml
$ # wait..
$ polyaxon tensorboard -g 1 start
```

### Expected behavior
No error.

### Environment
Kubernetes 1.17 using Kubeadm on a local cluster.

Let me know if you need more info.

**Comment by mouradmourafiq** [comment] 2020-01-21 17:12
This was fixed in #658
We need to push a new chart version.

**Comment by mouradmourafiq** [comment] 2020-01-21 17:24
Please run: `helm update` and upgrade you Polyaxon deployment and try again, it should work.

Feel free to reopen.

**Comment by vakker** [comment] 2020-01-27 19:42
When is this going to be rolled out? The current chart version is still 0.6.0.

**Comment by mouradmourafiq** [comment] 2020-01-27 19:44
Did you run `helm update` and redeployed, it should work with 0.6 chart?

**Comment by vakker** [comment] 2020-01-28 09:19
Yes, I did `help repo update` and `helm upgrade polyaxon polyaxon/polyaxon --namespace=polyaxon -f config.yml`. I'm using Helm 3 if that makes any difference.
Then I just rerun the polyaxon commands in the same project dir as before `polyaxon tensorboard -g 1 start`.

**Comment by mouradmourafiq** [comment] 2020-01-28 09:51
Can you run the upgrade command with `helm upgrade polyaxon polyaxon/polyaxon --namespace=polyaxon -f config.yml --debug --dry-run | grep apiGroups` and past the result here?

**Comment by vakker** [comment] 2020-01-28 10:02
Here you go:
```
$ helm upgrade polyaxon polyaxon/polyaxon --namespace=polyaxon -f config.yml --debug --dry-run | grep apiGroups
upgrade.go:79: [debug] preparing upgrade for polyaxon
upgrade.go:87: [debug] performing update for polyaxon
upgrade.go:220: [debug] dry run for polyaxon
  - apiGroups: [""]
  - apiGroups: ["metrics.k8s.io"]
  - apiGroups: [""]
  - apiGroups: [""]
  - apiGroups: ["batch"]
  - apiGroups: [""]
  - apiGroups: ["", "apps", "extensions"]
  - apiGroups: ["", "extensions"]
  - apiGroups: ["metrics.k8s.io"]
  - apiGroups: ["", "*"]
  - apiGroups: ["kubeflow.org"]
  - apiGroups: ["core.polyaxon.com"]
  - apiGroups: ["apiextensions.k8s.io"]
  - apiGroups: [""]
  - apiGroups: ["metrics.k8s.io"]
  - apiGroups: ["", "*"]
  - apiGroups: ["kubeflow.org"]
  - apiGroups: ["core.polyaxon.com"]
  - apiGroups: ["apiextensions.k8s.io"]
```

**Comment by mouradmourafiq** [comment] 2020-01-28 10:04
Ok, so the change is there `apiGroups: ["", "apps", "extensions"]`. I guess that it does not get applied, one way to ensure to it does is by deleting the service account manually, and then upgrade.

**Comment by vakker** [comment] 2020-01-28 10:51
I tried to delete and upgrade with the service accounts and the roles as well, but it's still the same.
If I run `k describe -n polyaxon roles.rbac.authorization.k8s.io polyaxon-polyaxon-role | grep extensions` I get:
```
  deployments.extensions                          []                 []              [get create patch delete list]
  ingresses.extensions                            []                 []              [get create patch delete list]
  replicasets.extensions                          []                 []              [get create patch delete list]
  services.extensions                             []                 []              [get create patch delete list]
  customresourcedefinitions.apiextensions.k8s.io  []                 []              [get watch list create delete patch]
```
So I assume that's correct.

But after checking the error, it's actually not the same 403 response, but a 404:
```
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s
/manager.py", line 316, in create_or_update_deployment return self.create_deployment(name=name, 
body=body), True File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 302, in 
create_deployment namespace=self.namespace, body=body File "/usr/local/lib/python3.7/site-
packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 175, in 
create_namespaced_deployment (data) = 
self.create_namespaced_deployment_with_http_info(namespace, body, **kwargs) File "/usr/local
/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 266, in 
create_namespaced_deployment_with_http_info collection_formats=collection_formats) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api 
_return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local
/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api 
_request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client
/api_client.py", line 377, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes
/client/rest.py", line 266, in POST body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes
/client/rest.py", line 222, in request raise ApiException(http_resp=r) 
kubernetes.client.rest.ApiException: (404) Reason: Not Found HTTP response headers: 
HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 28 Jan 2020 10:40:38 GMT', 
'Content-Length': '174'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":
{},"status":"Failure","message":"the server could not find the requested 
resource","reason":"NotFound","details":{},"code":404} During handling of the above exception, 
another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-
packages/polyaxon_k8s/manager.py", line 319, in create_or_update_deployment return 
self.update_deployment(name=name, body=body), False File "/usr/local/lib/python3.7/site-packages
/polyaxon_k8s/manager.py", line 309, in update_deployment name=name, 
namespace=self.namespace, body=body File "/usr/local/lib/python3.7/site-packages/kubernetes/client
/apis/extensions_v1beta1_api.py", line 4089, in patch_namespaced_deployment (data) = 
self.patch_namespaced_deployment_with_http_info(name, namespace, body, **kwargs) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 4189, 
in patch_namespaced_deployment_with_http_info collection_formats=collection_formats) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api 
_return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local
/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api 
_request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client
/api_client.py", line 393, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes
/client/rest.py", line 286, in PATCH body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes
/client/rest.py", line 222, in request raise ApiException(http_resp=r) 
kubernetes.client.rest.ApiException: (404) Reason: Not Found HTTP response headers: 
HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 28 Jan 2020 10:40:38 GMT', 
'Content-Length': '174'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":
{},"status":"Failure","message":"the server could not find the requested 
resource","reason":"NotFound","details":{},"code":404} During handling of the above exception, 
another exception occurred: Traceback (most recent call last): File "/polyaxon/polyaxon/scheduler
/tensorboard_scheduler.py", line 53, in start_tensorboard 
reconcile_url=get_tensorboard_reconcile_url(tensorboard.unique_name)) File "/polyaxon/polyaxon
/polypod/tensorboard.py", line 234, in start_tensorboard reraise=True) File "/usr/local/lib/python3.7
/site-packages/polyaxon_k8s/manager.py", line 322, in create_or_update_deployment raise 
PolyaxonK8SError(e) polyaxon_k8s.exceptions.PolyaxonK8SError: (404) Reason: Not Found HTTP 
response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 28 Jan 2020 
10:40:38 GMT', 'Content-Length': '174'}) HTTP response body: 
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find 
the requested resource","reason":"NotFound","details":{},"code":404} 
```

**Comment by mouradmourafiq** [comment] 2020-01-28 10:54
Maybe @valeriano-manassero can chime in here, did you encounter this issue after using the correct service account definition?

**Comment by valeriano-manassero** [comment] 2020-01-28 15:28
> ### Environment
> Kubernetes 1.17 using Kubeadm on a local cluster.

If I'm not wrong, K8s 1.17 is not supported atm. I just tried a completely new deployment on a Kubernetes with Helm3 and I see no issues. @mouradmourafiq can you confirm?

**Comment by mouradmourafiq** [comment] 2020-01-28 15:32
> If I'm not wrong, K8s 1.17 is not supported atm. 

I am not sure I get it, it's not supported or it's supported :) (because you said "no issue")

What k8s version did you deploy?

**Comment by valeriano-manassero** [comment] 2020-01-28 15:38
@mouradmourafiq sorry for not being clear. My testing system is actually a Kubernetes 1.15 and I got no issues like the one described here after a new installation from scratch.

If I remember well, Kubernetes 1.17 will require some helm chart adjustment to make Polyaxon work on it. Am I right?

**Comment by mouradmourafiq** [comment] 2020-01-28 15:42
I see, I misunderstood, thanks for clarifying.

Yes k8s 1.17 requires disabling the built-in database, but the issue @vakker is seeing, is probably related to the SA not having enough permission for creating deployment, which I believe was fixed in your PR.

**Comment by valeriano-manassero** [comment] 2020-01-28 16:11
I can confirm that K8s 1.15 + Helm3, installation from scratch, I get the quickstart project running and Tensorboard ok without issues.

**Comment by vakker** [comment] 2020-01-28 17:57
I can remove my current Polyaxon installation and start from scratch just to confirm that it's only the k8s version and not something else.

**Comment by mouradmourafiq** [comment] 2020-01-28 18:07
That would be helpful.

**Comment by vakker** [comment] 2020-01-28 23:00
Okey, I did a full uninstall/reinstall (I didn't remove the database) and it's the same 404 error.

**Comment by valeriano-manassero** [comment] 2020-01-29 09:02
@vakker just to be sure, what is the version of your polyaxon client?
Pls, can you attach the output of
```
polyaxon version
```

**Comment by vakker** [comment] 2020-01-29 09:29
```
Current cli version: 0.6.0.

Supported cli versions:
--------------  -----
latest_version  0.6.0
min_version     0.5.0
--------------  -----
```

Let me know if you need anything else.

**Comment by valeriano-manassero** [comment] 2020-01-29 09:54
@vakker I think it's possible there's a misunderstanding related polyaxon-client usage.

First, when you do an
```
polyaxon tensorboard -g 1 start
```
client will go by default on project with id 1. This can be confusing if you have multiple projects and maybe you are pointing to the wrong one.

I suggest to use
```
polyaxon tensorboard -p quick-start -g 1 start
````
declaring the project.

Btw, it's possible you are still referencing to the wrong experiment group.
It' better to check the id with:
```
polyaxon project -p quick-start groups
```
and set the -g parameter accordingly.

I saw that missing the right project or id can rsult in a 404 so maybe this is the issue. Can you pls check?

**Comment by vakker** [comment] 2020-01-29 16:30
I tried that, it's the same. I even created a new project as `quick-start2` and run an experiment group and then run `polyaxon tensorboard -p quick-start2 -g 4 start`.

As a side note, is that intentional that the IDs don't start from 1 for new projects but continue from the previous ID? I.e. instead of `root.quick-start2.4.81` I would have expected `root.quick-start2.1.1`.

**Comment by mouradmourafiq** [comment] 2020-01-29 16:33
> As a side note, is that intentional that the IDs don't start from 1 for new projects but continue from the previous ID? I.e. instead of root.quick-start2.4.81 I would have expected root.quick-start2.1.1.

Yes, it was initially a counter but due to concurrency it just made things slow and unstable, in v1 the platform is using uuids instead to remove the confusion.

**Comment by mouradmourafiq** [comment] 2020-02-01 23:16
This is a bug and it's not because of the chart, the client is using a deprecated/removed apis from k8s 1.17.

A fix has been merged, the chart was updated as well to use the latest postgresql, so I guess a release with all changes should be sometime next week or so.

Closing the issue. Thank you both for the help.

**Closed by mouradmourafiq** 2020-02-01 23:16 UTC
Labels: chart
