### ISSUE TITLE
cannot login user "root" with default password "rootpassword" while no config changed 

### ISSUE THREAD

**Issue by yh-xu** [polyaxon/polyaxon#637] opened 2019-12-24 10:00 UTC
I'm using polyaxon on Ubuntu 16.04. I was able to get polyaxon running and succuessfully run experiments. However, after I installed nvidia-docker2, k8s-device-plugin on node machines, I can no longer login polyaxon as "root/rootpassword" (I didn't customize default password) either from cli or dashboard. 

I currently have below pods running :
![image](https://user-images.githubusercontent.com/59196087/71407528-37a86280-2676-11ea-9342-03f36bd6a9e7.png)

polyaxon was set up with below configs:
ingress:
  enabled: false
serviceType: LoadBalancer
rabbitmq-ha:
  enabled: false
broker: redis
persistence:
  data:
    data1:
       mountPath: /opt
       hostPath:  /opt
       readOnly:  true
    data2:
       mountPath: /etc/environment
       hostPath: /etc/environment
       readOnly: true

I have no idea how to troubleshoot this problem. 
One thing might be culprit is docker was once crashed when installing nvidia-docker2 due to some mis-config, but anyway docker has got back and is now working normally.

**Comment by QipengZhou** [comment] 2019-12-26 05:54
ref: [setup/kubernetes/#deploy](https://docs.polyaxon.com/setup/kubernetes/#deploy)
check your password using the following command:
```bash
kubectl get secret --namespace polyaxon polyaxon-polyaxon-secret -o jsonpath="{.data.POLYAXON_ADMIN_PASSWORD}" | base64 --decode
```

**Comment by yh-xu** [comment] 2019-12-30 05:55
> ref: [setup/kubernetes/#deploy](https://docs.polyaxon.com/setup/kubernetes/#deploy)
> check your password using the following command:
> 
> ```shell
> kubectl get secret --namespace polyaxon polyaxon-polyaxon-secret -o jsonpath="{.data.POLYAXON_ADMIN_PASSWORD}" | base64 --decode
> ```

the command actually returned "rootpassword" as password, but it still couldn't login. I got another finding - in postgresql database, the db_user table had none user info. I guess postgresql pod somehow crashed and resumed but lost data?

**Comment by QipengZhou** [comment] 2019-12-30 07:31
If you not use persistence volume for postgresql, pod restart will lost data. You can create user manual use the following steps:
1. get polyaxon-api pod name
```bash
kubectl get pods -lrole=polyaxon-api -oname -n polyaxon
```
output something like "pod/polyaxon-polyaxon-api-28abcd8498-wv8qp"
2. enter polyaxon-api container in polyaxon-api
```bash
kubectl exec -it polyaxon-polyaxon-api-28abcd8498-wv8qp -c polyaxon-api -n polyaxon -- /bin/bash
```
3. in this container, run create user. ref: [creating-an-admin-user)](https://docs.djangoproject.com/en/3.0/intro/tutorial02/#creating-an-admin-user)
```bash
python polyaxon/manage.py createuser --superuser
```

**Comment by mouradmourafiq** [comment] 2020-01-13 00:45
I agree with @QipengZhou, most probably the node holding your db has either restarted or was preempted, and you probably lost data, you need to provide persistence for the DB. 

Please check this section of the [docs](https://docs.polyaxon.com/configuration/postgresql-ha/) for more details.

**Comment by huangyanjuner** [comment] 2020-03-31 13:35
I got same problem, and try the way as @QipengZhou said, but it still doesn't work. Pls help me.

**Comment by OodapowUiPath** [comment] 2020-05-12 20:28
@mouradmourafiq I got the same issue, but I use a external psql service. The db-init pod seems to run successfully but the database has no entry in the `db_user` table.

**Comment by mouradmourafiq** [comment] 2020-05-12 20:59
@OodapowUiPath did you use the pgsql on a previous deployed instance or was it a completely new deployment?

**Comment by OodapowUiPath** [comment] 2020-05-12 21:05
@mouradmourafiq it was a fresh deployment, I did do the following sequence of actions:
 * `helm install ...`
 * 'helm del ... --purge' (didn't use the --no-hooks flag)
 * change service type to node port in the config file
 * 'helm install ...' again

If you will leave a database purge cmd here I am willing to test it from scratch (I solved the issue by using the `python polyaxon/manage.py createuser --superuser` trick)

**Comment by mouradmourafiq** [comment] 2020-05-12 21:07
I asked because there's a `createuser` hook that only execute on initial deployment and not on upgrades, but your case is weird.

**Comment by OodapowUiPath** [comment] 2020-05-12 21:18
@mouradmourafiq I did the following test:
 * `helm del ...`
 * drop the database
 * create the database
 * check db_user table - not exist
 * `helm install ...`
 * wait for all the pods to be ready
 * check db_user table - exists but it has 0 rows
Needless to say, the UI login is not working.

**Comment by mouradmourafiq** [comment] 2020-05-12 21:20
when you

**Comment by OodapowUiPath** [comment] 2020-05-12 21:41
> when you run `helm install ...` do you see a job running after the the `sync-db` job?

It seems the `admin-user` job in not getting to a `Completed` state.

I did the install with a clean db all over again but this time I had a `kubectl get pods -n polyaxon --watch` running in another console.

The output of that (I removed the lines that are not important for this case):
```
polyaxon-sync-db-ll4lk                          0/1   Pending             0                                                                                                                                                                  0s
polyaxon-sync-db-ll4lk                          0/1   Pending             0            
polyaxon-sync-db-ll4lk                          0/1   Pending             0     7s
polyaxon-sync-db-ll4lk                          0/1   ContainerCreating   0     7s
polyaxon-sync-db-ll4lk                          1/1   Running             0     17s
polyaxon-sync-db-ll4lk                          0/1   Completed           0     26s
polyaxon-admin-user-tkn6w                       0/1   Pending             0     0s
polyaxon-admin-user-tkn6w                       0/1   Pending             0     0s
polyaxon-admin-user-tkn6w                       0/1   ContainerCreating   0     0s
polyaxon-sync-db-ll4lk                          0/1   Terminating         0     28s
polyaxon-sync-db-ll4lk                          0/1   Terminating         0     28s
polyaxon-admin-user-tkn6w                       0/1   ContainerCreating   0     0s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     2s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     2s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     4s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     4s
```

The full output of that is this:
```
polyaxon-polyaxon-monitors-56949ff65f-j2wlv   0/1   Pending   0     0s
polyaxon-polyaxon-beat-9dc596896-tzznj        0/2   Pending   0     0s
polyaxon-polyaxon-events-74488b5d8f-gjhvl     0/1   Pending   0     0s
polyaxon-polyaxon-api-c5555659d-82fw7         0/2   Pending   0     0s
polyaxon-polyaxon-hpsearch-85bd697d4b-9l2nx   0/1   Pending   0     0s
polyaxon-polyaxon-beat-9dc596896-tzznj        0/2   Pending   0     0s
polyaxon-polyaxon-monitors-56949ff65f-j2wlv   0/1   Pending   0     0s
polyaxon-polyaxon-events-74488b5d8f-gjhvl     0/1   Pending   0     0s
polyaxon-polyaxon-api-c5555659d-82fw7         0/2   Pending   0     0s
polyaxon-polyaxon-hpsearch-85bd697d4b-9l2nx   0/1   Pending   0     0s
polyaxon-redis-slave-0                        0/1   Pending   0     0s
polyaxon-polyaxon-scheduler-65fbbb9b67-pzlsk   0/1   Pending   0     0s
polyaxon-redis-slave-0                         0/1   Pending   0     0s
polyaxon-polyaxon-beat-9dc596896-tzznj         0/2   ContainerCreating   0     0                                                                                                                                                             s
polyaxon-polyaxon-scheduler-65fbbb9b67-pzlsk   0/1   Pending             0     0                                                                                                                                                             s
polyaxon-polyaxon-k8s-events-6b695bb8d8-v25sr   0/1   Pending             0                                                                                                                                                                  0s
polyaxon-docker-registry-7d479b4766-4wtmr       0/1   Pending             0                                                                                                                                                                  0s
polyaxon-polyaxon-k8s-events-6b695bb8d8-v25sr   0/1   Pending             0                                                                                                                                                                  0s
polyaxon-docker-registry-7d479b4766-4wtmr       0/1   Pending             0                                                                                                                                                                  0s
polyaxon-redis-master-0                         0/1   Pending             0                                                                                                                                                                  0s
polyaxon-redis-master-0                         0/1   Pending             0                                                                                                                                                                  0s
polyaxon-polyaxon-monitors-56949ff65f-j2wlv     0/1   ContainerCreating   0                                                                                                                                                                  1s
polyaxon-redis-slave-0                          0/1   Pending             0                                                                                                                                                                  2s
polyaxon-sync-db-ll4lk                          0/1   Pending             0                                                                                                                                                                  0s
polyaxon-sync-db-ll4lk                          0/1   Pending             0                                                                                                                                                                  0s
polyaxon-polyaxon-monitors-56949ff65f-j2wlv     0/1   ContainerCreating   0                                                                                                                                                                  3s
polyaxon-polyaxon-events-74488b5d8f-gjhvl       0/1   Pending             0                                                                                                                                                                  3s
polyaxon-polyaxon-beat-9dc596896-tzznj          0/2   ContainerCreating   0                                                                                                                                                                  3s
polyaxon-polyaxon-events-74488b5d8f-gjhvl       0/1   ContainerCreating   0                                                                                                                                                                  3s
polyaxon-polyaxon-api-c5555659d-82fw7           0/2   ContainerCreating   0     4s
polyaxon-polyaxon-hpsearch-85bd697d4b-9l2nx     0/1   ContainerCreating   0     5s
polyaxon-polyaxon-api-c5555659d-82fw7           0/2   ContainerCreating   0     5s
polyaxon-polyaxon-hpsearch-85bd697d4b-9l2nx     0/1   ContainerCreating   0     5s
polyaxon-redis-slave-0                          0/1   ContainerCreating   0     5s
polyaxon-polyaxon-scheduler-65fbbb9b67-pzlsk    0/1   ContainerCreating   0     6s
polyaxon-polyaxon-scheduler-65fbbb9b67-pzlsk    0/1   ContainerCreating   0     7s
polyaxon-polyaxon-k8s-events-6b695bb8d8-v25sr   0/1   Pending             0     7s
polyaxon-polyaxon-k8s-events-6b695bb8d8-v25sr   0/1   ContainerCreating   0     7s
polyaxon-docker-registry-7d479b4766-4wtmr       0/1   ContainerCreating   0     8s
polyaxon-redis-master-0                         0/1   ContainerCreating   0     8s
polyaxon-redis-master-0                         0/1   ContainerCreating   0     8s
polyaxon-docker-registry-7d479b4766-4wtmr       0/1   ContainerCreating   0     8s
polyaxon-sync-db-ll4lk                          0/1   Pending             0     7s
polyaxon-sync-db-ll4lk                          0/1   ContainerCreating   0     7s
polyaxon-redis-slave-0                          0/1   Running             0     9s
polyaxon-polyaxon-monitors-56949ff65f-j2wlv     1/1   Running             0     9s
polyaxon-polyaxon-events-74488b5d8f-gjhvl       1/1   Running             0     10s
polyaxon-docker-registry-7d479b4766-4wtmr       0/1   Running             0     11s
polyaxon-redis-master-0                         0/1   Running             0     11s
polyaxon-polyaxon-hpsearch-85bd697d4b-9l2nx     1/1   Running             0     13s
polyaxon-docker-registry-7d479b4766-4wtmr       1/1   Running             0     14s
polyaxon-redis-master-0                         1/1   Running             0     15s
polyaxon-polyaxon-scheduler-65fbbb9b67-pzlsk    1/1   Running             0     15s
polyaxon-polyaxon-k8s-events-6b695bb8d8-v25sr   1/1   Running             0     17s
polyaxon-sync-db-ll4lk                          1/1   Running             0     17s
polyaxon-polyaxon-beat-9dc596896-tzznj          2/2   Running             0     22s
polyaxon-polyaxon-api-c5555659d-82fw7           0/2   Running             0     24s
polyaxon-sync-db-ll4lk                          0/1   Completed           0     26s
polyaxon-admin-user-tkn6w                       0/1   Pending             0     0s
polyaxon-admin-user-tkn6w                       0/1   Pending             0     0s
polyaxon-admin-user-tkn6w                       0/1   ContainerCreating   0     0s
polyaxon-sync-db-ll4lk                          0/1   Terminating         0     28s
polyaxon-sync-db-ll4lk                          0/1   Terminating         0     28s
polyaxon-admin-user-tkn6w                       0/1   ContainerCreating   0     0s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     2s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     2s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     4s
polyaxon-admin-user-tkn6w                       0/1   Terminating         0     4s
polyaxon-redis-slave-0                          1/1   Running             0     38s
polyaxon-redis-slave-1                          0/1   Pending             0     0s
polyaxon-redis-slave-1                          0/1   Pending             0     0s
polyaxon-redis-slave-1                          0/1   ContainerCreating   0     0s
polyaxon-redis-slave-1                          0/1   ContainerCreating   0     0s
polyaxon-redis-slave-1                          0/1   Running             0     1s
polyaxon-redis-slave-1                          1/1   Running             0     7s
```

**Comment by mouradmourafiq** [comment] 2020-05-12 21:46
Are you using the default username/password or are you passing custom values?

**Comment by OodapowUiPath** [comment] 2020-05-12 21:49
The values are the default one and I added an email.

This is the config that I am using
```
https://github.com/Oodapow/research/blob/master/infrastructure/l3/polyaxon/yml/config.yml
```

This is the command I used for the install:
```
helm install polyaxon/polyaxon --name=polyaxon --namespace=polyaxon -f https://raw.githubusercontent.com/Oodapow/research/master/infrastructure/l3/polyaxon/yml/config.yml
```

**Comment by mouradmourafiq** [comment] 2020-07-02 15:41
Closing the issue, If you notice similar behaviour in v1.1+ feel free to reopen.

**Closed by mouradmourafiq** 2020-07-02 15:41 UTC

**Comment by yu-iskw** [comment] 2020-07-09 03:09
@mouradmourafiq I have the same issue with polyaxon 0.6.1. I just rebuild polyaxon 0.6.1, not v1.1. I can't login as root. As well as, I looked into `db_user` table to make sure if `root` exists or not. Surprisingly, `root` doesn't exist. Do you have any idea why `root` was not created?

```
polyaxon=> select * from db_user;
 id | password | last_login | is_superuser | username | first_name | last_name | email | is_staff | is_active | date_joined
----+----------+------------+--------------+----------+------------+-----------+-------+----------+-----------+-------------
(0 rows)
```

**Comment by mouradmourafiq** [comment] 2020-07-09 09:08
@yu-iskw I tried to reproduce this but I did not manage, the create-root job is still the same in v1.1 and it seems to work. I wonder how many people had this issue.
