### ISSUE TITLE
Temporary failure in name resolution in polyaxon-init-job

### ISSUE THREAD

**Issue by paktek123** [polyaxon/polyaxon#482] opened 2019-06-21 14:20 UTC
### Describe the bug

Hi, I seem to be getting an issue where when I run an experiment and the polyaxon-init-job container gets:

```requests.exceptions.ConnectionError: HTTPConnectionPool(host='polyaxon-polyaxon-api', port=80): Max retries exceeded with url: /api/v1/<redacted>/experiments/335526/imporsonatetoken/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b3121ac18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))```

polyaxon-polyaxon-api is the svc endpoint and is reachable by other jobs but this job always seems to fail whilst others succeed. The container lasts only a few milliseconds before it fails. I checked the `/etc/resolv.conf` and they seem to be there as expected but not sure why I get this temporary failure in name resolution. 

### To Reproduce
Run a polyaxon experiment in a busy cluster with many experiments being scheduled at the same time.

### Expected behavior
Experiment to start as expected.

### Environment
Kubernetes Version: v1.13.x
Polyaxon Version: 0.4.4
CNI: Calico v3.6

**Comment by mouradmourafiq** [comment] 2019-06-21 14:23
As discussed, 2 possible solutions that could solve this bug: 
 * new restarts attribute.
 * a simple retry on ConnectionError in the init container.

**Comment by mouradmourafiq** [comment] 2019-06-26 16:34
A retry mechanism has been added, and will be part of the coming release.

Feel free to reopen if you still see this problem after upgrading to v0.5.

**Comment by mouradmourafiq** [comment] 2019-07-22 22:29
I am not sure yet why this happens, I will try to debug it before next minor release.

**Comment by mouradmourafiq** [comment] 2019-07-23 21:57
The cause of the problem is how k8s manages EmptyDir. A fix is under way.

Closing the issue as it will be solved for v0.5.4.

**Closed by mouradmourafiq** 2019-07-23 21:57 UTC
Labels: bug, core

**Comment by brunowego** [comment] 2019-10-07 12:27
I'm getting a similar issue:

### Describe the bug

```sh
$ kubectl get pod \
  -l 'app=polyaxon-dockerizer,app.kubernetes.io/component=polyaxon-workers' \
  -o jsonpath='{.items..metadata.name}' \
  -n polyaxon | \
    xargs kubectl logs --all-containers=true -n polyaxon
Building: Step 1/5 : FROM atf.intranet.example.com:5001/big/library/python:3.0
Building:
Pushing ...
Building: ---> a4a6630aaeba
Building: Step 2/5 : ENV SHELL /bin/bash
Building:
Building: ---> Running in decafeb1732d
Building: Removing intermediate container decafeb1732d
Building: ---> 738223b7e513
Building: Step 3/5 : WORKDIR /code
Building:
Building: ---> Running in 605df1268887
Building: Removing intermediate container 605df1268887
Building: ---> a07e1734f2bf
Building: Step 4/5 : RUN pip3 install jupyterlab
Building:
Building: ---> Running in 6c8432594dae
Building: Looking in indexes: http://pypi.servicos.example.com/simple, http://atf.intranet.example.com/artifactory/api/pypi/bb-python-local/simple
Building: Collecting jupyterlab
Building:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37420598d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37426ba090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421b81d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421b8190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421b8110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421cb390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /artifactory/api/pypi/bb-python-local/simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421cb650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /artifactory/api/pypi/bb-python-local/simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421cb810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /artifactory/api/pypi/bb-python-local/simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421cc210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /artifactory/api/pypi/bb-python-local/simple/jupyterlab/

Building:   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f37421b8110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /artifactory/api/pypi/bb-python-local/simple/jupyterlab/

Building:   ERROR: Could not find a version that satisfies the requirement jupyterlab (from versions: none)

Building: ERROR: No matching distribution found for jupyterlab
```

### Environment

Polyaxon 0.5.6
K8s Client v1.16.1
K8s Server v1.13.10

**Comment by brunowego** [comment] 2019-10-07 12:30
More specific in `polyaxon-dockerizer-job`:

```sh
kubectl logs $(kubectl get pod -l 'app=polyaxon-dockerizer,app.kubernetes.io/component=polyaxon-workers' -o jsonpath='{.items[0].metadata.name}' -n polyaxon) polyaxon-dockerizer-job -n polyaxon
```
