### ISSUE TITLE
Experiment ID increase by project

### ISSUE THREAD

**Issue by QipengZhou** [polyaxon/polyaxon#474] opened 2019-06-14 10:32 UTC
### Feature motivation

Experiment id in the project has a bit confused. When I first run a experiment in a project the experiment id is not 1 if I have run some experiments in other project before.

### Feature description

Experiment ID in the project can begin from 1.

**Comment by entruv** [comment] 2019-06-21 07:11
Hey there, experiments are defined via a django model, the id is unique, can not be 1 for distinct experiments. 

But maybe creating a function such that Experiment.get_id_project_related() can "solve your problem".

**Comment by mouradmourafiq** [comment] 2019-06-21 07:29
I would say that this is not as easy as it might seem, experiments, as well as other primitives were annotated with this sequence [mixin](https://github.com/polyaxon/polyaxon/blob/master/polyaxon/db/models/abstract/sequence.py), but the issue is concurrency, since getting the current unique count at each point is not guaranteed. I think the creation is already slow because of the validations, but this one adds a consistency problem, that's the reason we removed it.

I will close this issue as `wontfix`.

**Closed by mouradmourafiq** 2019-06-21 07:29 UTC
