### ISSUE TITLE
High idle cpu usage caused by rabbitmq container

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polyaxon#309] opened 2019-01-09 14:32 UTC
Hi!

I am conducting some small scale testing on a minikube cluster and noticed high cpu usage (60-70%) by the rabbitmq container even after having the entire install idle for ~2 days. It is apparently a known issue and can be solved by upgrading the rabbitmq container.

https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/charts/rabbitmq/values.yaml#L4

https://github.com/helm/charts/issues/3855

**Comment by Mofef** [comment] 2019-02-08 09:28
Hi, I'm running `v0.3.8` on a kops cluster and I see ~30% cpu usage on a t2.small instance. Is that the expected improvement, from 60-70% down to 30%? Or is this maybe still an issue?

**Comment by Mofef** [comment] 2019-02-08 09:35
Oh and now that I had a look into helm/charts#3855: It seems that events like
```
  Warning  Unhealthy              6m (x32 over 31m)  kubelet, ip-172-20-41-234.eu-west-1.compute.internal  Liveness probe failed: Get http://100.96.7.36:80/_health/: dial tcp 100.96.7.36:80: getsockopt: connection refused
  Warning  Unhealthy              1m (x40 over 31m)  kubelet, ip-172-20-41-234.eu-west-1.compute.internal  Readiness probe failed: Get http://100.96.7.36:1337/_health/: dial tcp 100.96.7.36:1337: getsockopt: connection refused"
```
are likely caused by insufficient cpu resources...? (the instance got throttled to 25% because it ran out of cpu credits)

**Comment by mouradmourafiq** [comment] 2019-02-08 09:41
@Mofef can you pin which container is consuming the CPU?

**Comment by Mofef** [comment] 2019-02-08 09:57
docker stats
```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
10f62b4e120e        0.00%               10.27 MiB / 1.956 GiB   0.51%               0 B / 0 B           0 B / 0 B           3
199c85d03407        29.69%              24.21 MiB / 1.956 GiB   1.21%               0 B / 0 B           0 B / 0 B           6
671eeac9f887        0.00%               156 KiB / 1.956 GiB     0.01%               0 B / 0 B           0 B / 0 B           1
b39b8e463f15        169.82%             177.5 MiB / 1.956 GiB   8.86%               0 B / 0 B           0 B / 17.9 MB       139
4aa809897ccf        0.00%               7.965 MiB / 1.956 GiB   0.40%               0 B / 0 B           111 kB / 0 B        3
41dfad1465ac        0.00%               160 KiB / 1.956 GiB     0.01%               0 B / 0 B           0 B / 0 B           1
30ceea913bc0        0.00%               160 KiB / 1.956 GiB     0.01%               0 B / 0 B           0 B / 0 B           1
8da93bbd49ea        0.08%               11.89 MiB / 1.956 GiB   0.59%               0 B / 0 B           2.02 MB / 0 B       8
4d2328213951        0.00%               156 KiB / 1.956 GiB     0.01%               0 B / 0 B           12.3 kB / 0 B       1

```
docker ps
```
10f62b4e120e        polyaxon/polyaxon-api@sha256:69c6baae61a168b7387fd80f851f7f57d59759b5616a48bf9f095d9d926e908f                 "/bin/bash ./polya..."   About a minute ago   Up About a minute                       k8s_polyaxon-api_polyaxon-polyaxon-api-5b966d9768-jsb4h_polyaxon_e2b189b3-2b7e-11e9-b949-0acdd77d9302_7
199c85d03407        polyaxon/polyaxon-streams@sha256:bd70136d49972d3a7adeb96cc8dc659aecd2ccb8550c407ad50da46a74419cb2             "/bin/bash ./entry..."   2 minutes ago        Up 2 minutes                            k8s_polyaxon-streams_polyaxon-polyaxon-api-5b966d9768-jsb4h_polyaxon_e2b189b3-2b7e-11e9-b949-0acdd77d9302_8
671eeac9f887        k8s.gcr.io/pause-amd64:3.0                                                                                    "/pause"                 57 minutes ago       Up 57 minutes                           k8s_POD_polyaxon-polyaxon-api-5b966d9768-jsb4h_polyaxon_e2b189b3-2b7e-11e9-b949-0acdd77d9302_0
b39b8e463f15        rabbitmq@sha256:3eb2fa0f83914999846f831f14b900c0c85cea8e5d2db48ff73cf7defa12fe96                              "docker-entrypoint..."   13 hours ago         Up 13 hours                             k8s_polyaxon-rabbitmq_polyaxon-rabbitmq-5c97dc88-657tl_polyaxon_4a24f4bd-2b12-11e9-b949-0acdd77d9302_0
4aa809897ccf        polyaxon/polyaxon-monitor-resources@sha256:d028b9ce9978a11139498a86d7b2d384b027ada65e7c3e61feac01cb09fbd13c   "/bin/bash ./entry..."   13 hours ago         Up 13 hours                             k8s_polyaxon-resources_polyaxon-polyaxon-resources-4wkzc_polyaxon_7d0033fe-2b12-11e9-b949-0acdd77d9302_0
41dfad1465ac        k8s.gcr.io/pause-amd64:3.0                                                                                    "/pause"                 13 hours ago         Up 13 hours                             k8s_POD_polyaxon-rabbitmq-5c97dc88-657tl_polyaxon_4a24f4bd-2b12-11e9-b949-0acdd77d9302_0
30ceea913bc0        k8s.gcr.io/pause-amd64:3.0                                                                                    "/pause"                 13 hours ago         Up 13 hours                             k8s_POD_polyaxon-polyaxon-resources-4wkzc_polyaxon_7d0033fe-2b12-11e9-b949-0acdd77d9302_0
8da93bbd49ea        k8s.gcr.io/kube-proxy@sha256:7dda581722b4d1f6afc6d068d42d89b5b2ca4b7dba63642a3cf35dd901d05eac                 "/bin/sh -c 'mkfif..."   13 hours ago         Up 13 hours                             k8s_kube-proxy_kube-proxy-ip-172-20-41-234.eu-west-1.compute.internal_kube-system_6a2682cf7b93e410655d1afc480d2658_0
4d2328213951        k8s.gcr.io/pause-amd64:3.0                                                                                    "/pause"                 13 hours ago         Up 13 hours                             k8s_POD_kube-proxy-ip-172-20-41-234.eu-west-1.compute.internal_kube-system_6a2682cf7b93e410655d1afc480d2658_0
```

I'm pretty new to the whole docker and kubernetes space, so not sure if this is what you are asking for.

**Comment by Mofef** [comment] 2019-02-22 15:02
@mouradmourafiq Do you have an idea what could be the problem? Can I assist you with something?
Here is a log from the pod. Apparently connections ar constantly opened and get closed again

```
2019-02-22 14:43:02.527 [info] <0.26613.5> connection <0.26613.5> (100.96.19.19:42124 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:43:04.087 [info] <0.26628.5> accepting AMQP connection <0.26628.5> (100.96.19.18:35692 -> 100.96.18.24:5672)
2019-02-22 14:43:04.089 [info] <0.26628.5> connection <0.26628.5> (100.96.19.18:35692 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:43:04.289 [info] <0.26644.5> accepting AMQP connection <0.26644.5> (100.96.19.17:57546 -> 100.96.18.24:5672)
2019-02-22 14:43:04.290 [info] <0.26647.5> accepting AMQP connection <0.26647.5> (100.96.19.17:57548 -> 100.96.18.24:5672)
2019-02-22 14:43:04.310 [info] <0.26647.5> connection <0.26647.5> (100.96.19.17:57548 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:43:04.311 [info] <0.26644.5> connection <0.26644.5> (100.96.19.17:57546 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:43:04.395 [info] <0.26670.5> accepting AMQP connection <0.26670.5> (100.96.21.10:33930 -> 100.96.18.24:5672)
2019-02-22 14:43:04.396 [info] <0.26673.5> accepting AMQP connection <0.26673.5> (100.96.21.10:33932 -> 100.96.18.24:5672)
2019-02-22 14:43:04.456 [info] <0.26670.5> connection <0.26670.5> (100.96.21.10:33930 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:43:04.457 [info] <0.26673.5> connection <0.26673.5> (100.96.21.10:33932 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:44:53.270 [info] <0.26785.5> accepting AMQP connection <0.26785.5> (100.96.21.8:42366 -> 100.96.18.24:5672)
2019-02-22 14:44:53.291 [info] <0.26785.5> connection <0.26785.5> (100.96.21.8:42366 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:45:23.268 [error] <0.26503.5> closing AMQP connection <0.26503.5> (100.96.21.8:42078 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:45:27.495 [error] <0.26528.5> closing AMQP connection <0.26528.5> (100.96.19.19:42034 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:45:27.556 [error] <0.26531.5> closing AMQP connection <0.26531.5> (100.96.19.19:42036 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:45:29.525 [error] <0.26558.5> closing AMQP connection <0.26558.5> (100.96.19.19:42044 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:45:31.166 [error] <0.26573.5> closing AMQP connection <0.26573.5> (100.96.19.19:42046 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:46:02.552 [error] <0.26613.5> closing AMQP connection <0.26613.5> (100.96.19.19:42124 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:46:04.133 [error] <0.26628.5> closing AMQP connection <0.26628.5> (100.96.19.18:35692 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:46:04.481 [error] <0.26673.5> closing AMQP connection <0.26673.5> (100.96.21.10:33932 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:47:04.336 [error] <0.26647.5> closing AMQP connection <0.26647.5> (100.96.19.17:57548 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
2019-02-22 14:47:23.408 [info] <0.26998.5> accepting AMQP connection <0.26998.5> (100.96.21.8:42638 -> 100.96.18.24:5672)
2019-02-22 14:47:23.430 [info] <0.26998.5> connection <0.26998.5> (100.96.21.8:42638 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:47:53.337 [error] <0.26785.5> closing AMQP connection <0.26785.5> (100.96.21.8:42366 -> 100.96.18.24:5672):
missed heartbeats from client, timeout: 60s
```

when greping for a specific client ip it becomes more obvious. Also more than one connection is opened per client (in this case the polyaxon-polyaxon-api pod)
```
2019-02-22 13:56:29.489 [info] <0.23470.5> accepting AMQP connection <0.23470.5> (100.96.19.19:34814 -> 100.96.18.24:5672)
2019-02-22 13:56:29.490 [info] <0.23473.5> accepting AMQP connection <0.23473.5> (100.96.19.19:34816 -> 100.96.18.24:5672)
2019-02-22 13:56:29.495 [info] <0.23473.5> connection <0.23473.5> (100.96.19.19:34816 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 13:56:29.496 [info] <0.23470.5> connection <0.23470.5> (100.96.19.19:34814 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 13:56:30.972 [info] <0.23504.5> accepting AMQP connection <0.23504.5> (100.96.19.19:34818 -> 100.96.18.24:5672)
2019-02-22 13:56:30.974 [info] <0.23504.5> connection <0.23504.5> (100.96.19.19:34818 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 13:56:42.700 [info] <0.23532.5> accepting AMQP connection <0.23532.5> (100.96.19.19:34844 -> 100.96.18.24:5672)
2019-02-22 13:56:42.703 [info] <0.23532.5> connection <0.23532.5> (100.96.19.19:34844 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 13:59:29.518 [error] <0.23473.5> closing AMQP connection <0.23473.5> (100.96.19.19:34816 -> 100.96.18.24:5672):
2019-02-22 13:59:29.518 [error] <0.23470.5> closing AMQP connection <0.23470.5> (100.96.19.19:34814 -> 100.96.18.24:5672):
2019-02-22 13:59:30.997 [error] <0.23504.5> closing AMQP connection <0.23504.5> (100.96.19.19:34818 -> 100.96.18.24:5672):
2019-02-22 13:59:42.785 [error] <0.23532.5> closing AMQP connection <0.23532.5> (100.96.19.19:34844 -> 100.96.18.24:5672):
2019-02-22 14:42:27.460 [info] <0.26528.5> accepting AMQP connection <0.26528.5> (100.96.19.19:42034 -> 100.96.18.24:5672)
2019-02-22 14:42:27.461 [info] <0.26531.5> accepting AMQP connection <0.26531.5> (100.96.19.19:42036 -> 100.96.18.24:5672)
2019-02-22 14:42:27.541 [info] <0.26528.5> connection <0.26528.5> (100.96.19.19:42034 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:42:27.543 [info] <0.26531.5> connection <0.26531.5> (100.96.19.19:42036 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:42:29.493 [info] <0.26558.5> accepting AMQP connection <0.26558.5> (100.96.19.19:42044 -> 100.96.18.24:5672)
2019-02-22 14:42:29.512 [info] <0.26558.5> connection <0.26558.5> (100.96.19.19:42044 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:42:31.132 [info] <0.26573.5> accepting AMQP connection <0.26573.5> (100.96.19.19:42046 -> 100.96.18.24:5672)
2019-02-22 14:42:31.153 [info] <0.26573.5> connection <0.26573.5> (100.96.19.19:42046 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:43:02.507 [info] <0.26613.5> accepting AMQP connection <0.26613.5> (100.96.19.19:42124 -> 100.96.18.24:5672)
2019-02-22 14:43:02.527 [info] <0.26613.5> connection <0.26613.5> (100.96.19.19:42124 -> 100.96.18.24:5672): user 'guest' authenticated and granted access to vhost '/'
2019-02-22 14:45:27.495 [error] <0.26528.5> closing AMQP connection <0.26528.5> (100.96.19.19:42034 -> 100.96.18.24:5672):
2019-02-22 14:45:27.556 [error] <0.26531.5> closing AMQP connection <0.26531.5> (100.96.19.19:42036 -> 100.96.18.24:5672):
2019-02-22 14:45:29.525 [error] <0.26558.5> closing AMQP connection <0.26558.5> (100.96.19.19:42044 -> 100.96.18.24:5672):
2019-02-22 14:45:31.166 [error] <0.26573.5> closing AMQP connection <0.26573.5> (100.96.19.19:42046 -> 100.96.18.24:5672):
2019-02-22 14:46:02.552 [error] <0.26613.5> closing AMQP connection <0.26613.5> (100.96.19.19:42124 -> 100.96.18.24:5672):
```

**Comment by mouradmourafiq** [comment] 2019-02-22 15:35
I reduced the frequency of the probes. 

After the v0.4.0, I think it could be a good think to try and invest some time into upgrading rabbitmq subchart to the latest version. A lot of the changes in the current modified chart are already implemented, also it seems that changed the probes execution to use `curl` instead of `rabbitmqctl`, as well as using the `ulimit`.

**Comment by Mofef** [comment] 2019-02-22 16:15
Amazing, thanks! That seems to completely solve the issue for me. CPU utilization went down to 3.5% :+1:

**Comment by mouradmourafiq** [comment] 2019-02-22 16:20
the v0.4.0 package will be released today with the fix.

And I will try to upgrade the subchart after the v0.4.0.

**Comment by mouradmourafiq** [comment] 2019-04-27 12:18
Polyaxn will be using the std stable rabbitmq in the next release, v0.5, plus the possibility to use an external/managed rabbitmq.

Closing this for now, feel free to reopen in the future if the issue persists.

**Closed by mouradmourafiq** 2019-04-27 12:18 UTC
Labels: WIP, enhancement
