### ISSUE TITLE
Polyaxon run -u should not re-trigger build 

### ISSUE THREAD

**Issue by innovia** [polyaxon/polyaxon#148] opened 2018-07-24 19:21 UTC
### Describe the bug
seems like changing the polyaxonfile.yaml triggers a new build which is time consuming 
changing the environment or the cmd should not trigger the build.

**Comment by honnibal** [comment] 2018-09-18 13:42
As a workaround, you could consider moving your command code into a script, so that the polyaxonfile.yml doesn't change when you update your run script. This also makes it easier to debug your run script locally.

**Comment by jorgemf** [comment] 2018-09-18 13:59
@honnibal I don't change the polyaxonfile and still triggers a new build

**Comment by mouradmourafiq** [comment] 2018-09-18 14:09
@jorgemf do you change something in the repo? Do you run it with `-u`?

Just to add some explanation to this, the build is triggered for the following reasons:
 * When using an image without a tag, Polyaxon assumes latest so it forces a new build, if nothing changed the build will be fast anyways.
 * When the last build was made more than X hours, this is an assumption to handle cases where the cluster was stopped and the regitry has no persistence, the platform just rebuilds. Maybe shoule be configurable or may be needs more checks.
 * When the build section has `nocache: true`.
 * when a file is changed in the repo, including the polyaxonfiles, you can add the polyaxonfiles to `.polyaxonignore` to ignore them, in all cases the polyaxonfile config is always stored in the db, also, in case just some params are changed in the polyaxonfile, you can run without the need of `-u` option.

**Comment by mouradmourafiq** [comment] 2018-09-18 14:30
@jorgemf This is a valid case for rebuilding, I might have misunderstood your previous comment. I think the issue is related to the fact that Polyaxon retriggers a build although no code was changed, only some sections in the polyaxonfile that should not trigger a build.

In any case, I am very open to suggestions on how to enhance the workflow.

**Comment by jorgemf** [comment] 2018-09-18 14:35
I think the point is that rebuilds are expensive. How difficult is to use a base yaml file for a base build and then create new ones from the base one (as importing a docker image from other docker images).  For example, we can have a base build file which includes all dependencies that need to be downloaded (python packages etc), this would be mostly the current build section. Then we have other builds with the command line options and experiments setups, resources, etc, all other sections that are not build. Would this also solve your issue @innovia?

**Comment by honnibal** [comment] 2018-09-21 21:29
When I trigger an experiment group, I get a new build for each experiment being triggered. This isn't the intended behaviour, right? I think the user should expect that the whole group will use the same container, so we should be able to only build once.

**Comment by mouradmourafiq** [comment] 2018-09-21 22:46
I am very aware of this, I am still thinking if I should "fix"/update the behaviour or not, I will explain: the polyaxonfile has templating, with jinja, and supports some operators that could change the build of experiments inside a group. Normally during the scheduling, if a build is found with the same characteristics, then no build is created, and jobs will subscribe to the events of the currently running build. Since the experiments creation in the group is done asynchronously, what could happen is that some/or all of the experiments could check for a build, not find any and start their own. I was wondering if I should just remove the templating from the build and add it to the documentation, or just point out that one can create a build, and then launch the groups.

I can see that it's confusing, so one solution is that I will assume that people will always expect one build for all experiments.

**Comment by mouradmourafiq** [comment] 2020-01-13 15:59
V1 has a flexible caching mechanism for runs based on the inputs/params, plus possibility to customize/override default behavior per run:

```
// Cache specification
message Cache {
    // Optional flag to disable cache
    bool disable = 1;

    // Optional TTL for cache before it gets invalidated automatically
    int32 ttl = 2;

    // Optional Input' names to consider for the cache, by default all inputs will be considered if empty
    repeated string inputs = 3;
}
```

Additionally the build step is not required anymore, users can provide their own docker image to use.

Closing the issue.

**Closed by mouradmourafiq** 2020-01-13 15:59 UTC
Labels: enhancement, in-v1
