### ISSUE TITLE
Cannot create notebooks without uploading the code

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#407] opened 2019-03-23 11:27 UTC
Create a new project. Try to start a notebook without uploading the code first (option -u). The build fails without any error message.

**Comment by mouradmourafiq** [comment] 2019-03-23 12:55
This is for now an intended behaviour(you create a notebook to explore your code). But I can see that users would want to start from scratch, either just exploring or build the code on the platform itself.

I will mark this as a feature request, a solution is coming together slowly to handle several edge cases.

**Comment by jorgemf** [comment] 2019-03-23 16:45
@mouradmourafiq For me the main issues is that there wasn't any error message. With a message it would be ok for me.

**Comment by mouradmourafiq** [comment] 2019-03-23 17:18
Completely agree, the same issue happens with experiments when the project is not initialized or not linked to a git project.

**Comment by mouradmourafiq** [comment] 2020-01-13 16:06
Code initialization is not required for running jobs/experiments/notebooks/dashboards in v1. Besides many git repos can be used per run, users can decide to pull the code themselves or users the git initializer.

Closing this issue as it wont implemented in v0.x.

**Closed by mouradmourafiq** 2020-01-13 16:06 UTC
Labels: feature, in-v1
