### ISSUE TITLE
Error on 'polyaxon experiment -xp 1 resources'

### ISSUE THREAD

**Issue by naetherm** [polyaxon/polyaxon#174] opened 2018-08-31 07:39 UTC
### Describe the bug
Following the quick start tutorial [0] of the documentation and executing the command, mentioned in the subject, we'll receive the error message:
```
error from callback <function BaseClient.socket.<locals>.<lambda> at 0x7fd310a29510>: __init__() missing 9 required positional arguments: 'job_uuid', 'experiment_uuid', 'job_name', 'container_id', 'n_cpus', 'cpu_percentage', 'percpu_percentage', 'memory_used', and 'memory_limit'
Session ended
```

### To Reproduce
Following the quick start tutorial from [0]. We additionally have the problem that the build process is currently failing, but the important part for this bug is that we receive the mentioned error message after trying `polyaxon experiment -xp 1 resources`.

### Expected behavior
Something similar to: 
```
    Job                           Mem Usage / Limit    CPU% - CPUs
--------------------------------  -------------------  ---------------
master.1                          0.47 Gb / 6.79 Gb    120.47% - 6
```

### Environment
OS: Ubuntu 16.04
Kubernetes: 1.11.1, Overlay Network: Weave.Net
Helm: 2.9.1

[0] https://docs.polyaxon.com/quick_start/

**Comment by mouradmourafiq** [comment] 2018-08-31 08:56
@naetherm I was not able to reproduce the issue. But one thing regarding resources, it's going to change, there will be a requirement to have Prometheus deployed as well, there are a lot of issues tracking the correct values with the current method.

I more interested by knowing the issue related to the build, can you elaborate a bit more on that.

**Comment by mouradmourafiq** [comment] 2018-10-01 11:54
@naetherm good to know, let me know if you encounter any issues. I will close this issue for now.

**Closed by mouradmourafiq** 2018-10-01 11:54 UTC

**Comment by matteosimone** [comment] 2018-11-27 18:01
I was able to reproduce this problem following the quick start guide using minikube. The kubernetes dashboard shows that all of my deployments and pods are ok so I am not sure what is wrong. I have only been following the quick start guide.

```
> polyaxon experiment -xp 1 resources 

error from callback <function SocketTransportMixin.socket.<locals>.<lambda> at 0x115301ea0>: __init__() missing 9 required positional arguments: 'job_uuid', 'experiment_uuid', 'job_name', 'container_id', 'n_cpus', 'cpu_percentage', 'percpu_percentage', 'memory_used', and 'memory_limit'
Session ended
```

```
> polyaxon version
Current cli version: 0.3.3.


Supported cli versions:

--------------  -----
latest_version  0.3.2
min_version     0.3.0
--------------  -----

> polyaxon version --platform

Current platform version: 0.3.2.


Supported platform versions:

--------------  -----
latest_version  0.3.2
min_version     0.3.1
--------------  -----
```
