### ISSUE TITLE
Get '(403) Reason: Forbidden HTTP' error when running the quick start example (running Polyaxon on Minikube)

### ISSUE THREAD

**Issue by manuelsh** [polyaxon/polyaxon#644] opened 2020-01-01 23:11 UTC
### Describe the bug
When running the quick-start experiment, it doesn't build it. I get an error:
Could not start build job encountered a "PolyaxonK8SError exception".

### To Reproduce
I have Minikube and the polyaxon CLI installed. Then I run the following script, without RBAC (that may be the issue?):
```
# start minikube
minikube start --cpus 4 --memory 8192 --disk-size=40g --vm-driver=virtualbox --kubernetes-version=1.15.4

# prepare helm
helm init --service-account tiller
kubectl --namespace kube-system create sa tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller

print create namespace
kubectl create namespace polyaxon

# Install polyaxon:
print add polyaxon repo
helm repo add polyaxon https://charts.polyaxon.com
helm repo update

print validate config
polyaxon admin deploy -f polyaxon_config.yml --check

print deploy polyaxon
polyaxon admin deploy -f polyaxon_config.yml

print getting application URL
export POLYAXON_IP=$(minikube ip)
export POLYAXON_PORT=$(kubectl get --namespace polyaxon -o jsonpath="{.spec.ports[0].nodePort}" services polyaxon-polyaxon-api)
echo http://$POLYAXON_IP:$POLYAXON_PORT

print setting up CLI
polyaxon config set --host=$POLYAXON_IP --port=$POLYAXON_PORT

print user is root
print password is (without the last %)
kubectl get secret --namespace polyaxon polyaxon-polyaxon-secret -o jsonpath="{.data.POLYAXON_ADMIN_PASSWORD}" | base64 --decode
minikube service -n polyaxon polyaxon-polyaxon-api
```
Then I run the example in:

https://docs.polyaxon.com/concepts/quick-start-internal-repo/

### Expected behavior
I expect the first experiment to run, however, instead of that it fails, and when I check the build issues, I get:
```
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py",
line 202, in create_or_update_pod return self.create_pod(name=name, body=body), 
True File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 189, 
in create_pod resp = self.k8s_api.create_namespaced_pod(namespace=self.namespace,
 body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py",
 line 6115, in create_namespaced_pod (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs) 
File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6206, in 
create_namespaced_pod_with_http_info collection_formats=collection_formats) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api 
_return_http_data_only, collection_formats, _preload_content, _request_timeout) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api 
_request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-
packages/kubernetes/client/api_client.py", line 377, in request body=body) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 266, in POST body=body) 
File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise 
ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP 
response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 01 Jan 2020 22:59:47 GMT', 'Content-Length': '286'}) HTTP response body: 
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User 
\"system:serviceaccount:polyaxon:default\" cannot create resource \"pods\" in API group \"\" in the 
namespace \"polyaxon\"","reason":"Forbidden","details":{"kind":"pods"},"code":403} During handling of 
the above exception, another exception occurred: Traceback (most recent call last): File 
"/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 205, in create_or_update_pod 
return self.update_pod(name=name, body=body), False File "/usr/local/lib/python3.7/site-
packages/polyaxon_k8s/manager.py", line 196, in update_pod body=body) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 15568, in 
patch_namespaced_pod (data) = self.patch_namespaced_pod_with_http_info(name, namespace, body, 
**kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 
15662, in patch_namespaced_pod_with_http_info collection_formats=collection_formats) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api 
_return_http_data_only, collection_formats, _preload_content, _request_timeout) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api 
_request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-
packages/kubernetes/client/api_client.py", line 393, in request body=body) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH body=body) File 
"/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise 
ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response 
headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 
'Wed, 01 Jan 2020 22:59:47 GMT', 'Content-Length': '384'}) HTTP response body: 
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plx-build-
5eccde694ad8466caffba33d86de07d0\" is forbidden: User \"system:serviceaccount:polyaxon:default\" 
cannot patch resource \"pods\" in API group \"\" in the namespace 
\"polyaxon\"","reason":"Forbidden","details":{"name":"plx-build-
5eccde694ad8466caffba33d86de07d0","kind":"pods"},"code":403} During handling of the above 
exception, another exception occurred: Traceback (most recent call last): File 
"/polyaxon/polyaxon/scheduler/dockerizer_scheduler.py", line 141, in start_dockerizer 
reconcile_url=get_build_reconcile_url(build_job.unique_name)) File 
"/polyaxon/polyaxon/polypod/dockerizer.py", line 234, in start_dockerizer pod_resp, _ = 
self.create_or_update_pod(name=resource_name, body=pod, reraise=True) File 
"/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 208, in create_or_update_pod 
raise PolyaxonK8SError(e) polyaxon_k8s.exceptions.PolyaxonK8SError: (403) Reason: Forbidden HTTP 
response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 
'nosniff', 'Date': 'Wed, 01 Jan 2020 22:59:47 GMT', 'Content-Length': '384'}) HTTP response body: 
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plx-build-
5eccde694ad8466caffba33d86de07d0\" is forbidden: User \"system:serviceaccount:polyaxon:default\" 
cannot patch resource \"pods\" in API group \"\" in the namespace 
\"polyaxon\"","reason":"Forbidden","details":{"name":"plx-build-
5eccde694ad8466caffba33d86de07d0","kind":"pods"},"code":403}
```

**Comment by L-GCHQ** [comment] 2020-02-12 16:26
I can second this error on minikube with no RBAC:

`Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 212, in create_or_update_pod return self.create_pod(name=name, body=body), True File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 199, in create_pod resp = self.k8s_api.create_namespaced_pod(namespace=self.namespace, body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6115, in create_namespaced_pod (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6206, in create_namespaced_pod_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 266, in POST body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Feb 2020 16:20:20 GMT', 'Content-Length': '286'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:polyaxon:default\" cannot create resource \"pods\" in API group \"\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"kind":"pods"},"code":403} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 215, in create_or_update_pod return self.update_pod(name=name, body=body), False File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 205, in update_pod name=name, namespace=self.namespace, body=body File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 15470, in patch_namespaced_pod (data) = self.patch_namespaced_pod_with_http_info(name, namespace, body, **kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 15570, in patch_namespaced_pod_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 393, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Feb 2020 16:20:20 GMT', 'Content-Length': '384'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plx-build-4d436ccd42694ac9b969a648307aa039\" is forbidden: User \"system:serviceaccount:polyaxon:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"name":"plx-build-4d436ccd42694ac9b969a648307aa039","kind":"pods"},"code":403} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/polyaxon/polyaxon/scheduler/dockerizer_scheduler.py", line 141, in start_dockerizer reconcile_url=get_build_reconcile_url(build_job.unique_name)) File "/polyaxon/polyaxon/polypod/dockerizer.py", line 234, in start_dockerizer pod_resp, _ = self.create_or_update_pod(name=resource_name, body=pod, reraise=True) File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 218, in create_or_update_pod raise PolyaxonK8SError(e) polyaxon_k8s.exceptions.PolyaxonK8SError: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Feb 2020 16:20:20 GMT', 'Content-Length': '384'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plx-build-4d436ccd42694ac9b969a648307aa039\" is forbidden: User \"system:serviceaccount:polyaxon:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"name":"plx-build-4d436ccd42694ac9b969a648307aa039","kind":"pods"},"code":403}`

**Comment by mouradmourafiq** [comment] 2020-02-12 16:28
Can you try it with this config: https://docs.polyaxon.com/setup/minikube/#rbac

**Comment by L-GCHQ** [comment] 2020-02-12 16:51
We've re run it with RBAC enabled, unfortunately it looks like the same error turns up: 

`
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 212, in create_or_update_pod return self.create_pod(name=name, body=body), True File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 199, in create_pod resp = self.k8s_api.create_namespaced_pod(namespace=self.namespace, body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6115, in create_namespaced_pod (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 6206, in create_namespaced_pod_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 266, in POST body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Feb 2020 16:47:03 GMT', 'Content-Length': '286'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:polyaxon:default\" cannot create resource \"pods\" in API group \"\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"kind":"pods"},"code":403} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 215, in create_or_update_pod return self.update_pod(name=name, body=body), False File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 205, in update_pod name=name, namespace=self.namespace, body=body File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 15470, in patch_namespaced_pod (data) = self.patch_namespaced_pod_with_http_info(name, namespace, body, **kwargs) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 15570, in patch_namespaced_pod_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 393, in request body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 286, in PATCH body=body) File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Feb 2020 16:47:03 GMT', 'Content-Length': '384'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plx-build-f93d43a7912b42079d7912f6224929a7\" is forbidden: User \"system:serviceaccount:polyaxon:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"name":"plx-build-f93d43a7912b42079d7912f6224929a7","kind":"pods"},"code":403} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/polyaxon/polyaxon/scheduler/dockerizer_scheduler.py", line 141, in start_dockerizer reconcile_url=get_build_reconcile_url(build_job.unique_name)) File "/polyaxon/polyaxon/polypod/dockerizer.py", line 234, in start_dockerizer pod_resp, _ = self.create_or_update_pod(name=resource_name, body=pod, reraise=True) File "/usr/local/lib/python3.7/site-packages/polyaxon_k8s/manager.py", line 218, in create_or_update_pod raise PolyaxonK8SError(e) polyaxon_k8s.exceptions.PolyaxonK8SError: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Feb 2020 16:47:03 GMT', 'Content-Length': '384'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plx-build-f93d43a7912b42079d7912f6224929a7\" is forbidden: User \"system:serviceaccount:polyaxon:default\" cannot patch resource \"pods\" in API group \"\" in the namespace \"polyaxon\"","reason":"Forbidden","details":{"name":"plx-build-f93d43a7912b42079d7912f6224929a7","kind":"pods"},"code":403}
`

**Comment by mouradmourafiq** [comment] 2020-02-12 16:56
Did you then try to set minikube with no rbac: https://docs.polyaxon.com/setup/minikube/#disabling-rbac-and-ingress

**Comment by mouradmourafiq** [comment] 2020-02-12 16:58
I am not sure anymore, but before, in order for some settings to atke effect, minikube required to delete and restart with those settings.

**Comment by L-GCHQ** [comment] 2020-02-13 09:28
On our first attempt we disabled RBAC: We left everything as is in the tutorial. 
After being asked to try with RBAC we did minikube delete and restarted adding the additional input to the minikube start up and setting rbac enabled to true.

We did not change the ingress settings, is this needed?

**Comment by mouradmourafiq** [comment] 2020-02-13 10:21
Ingress is disabled by default.
Can you check the service account created: `kubectl describe -n polyaxon sa`

**Comment by L-GCHQ** [comment] 2020-02-13 10:35
Here is the output of `kubectl describe -n polyaxon sa`

```
Name:                default
Namespace:           polyaxon
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   default-token-zqrvd
Tokens:              default-token-zqrvd
Events:              <none>


Name:                polyaxon-polyaxon-serviceaccount
Namespace:           polyaxon
Labels:              app=polyaxon-polyaxon-serviceaccount
                     app.kubernetes.io/component=polyaxon-config
                     app.kubernetes.io/instance=polyaxon-0.6.0
                     app.kubernetes.io/managed-by=helm
                     app.kubernetes.io/name=polyaxon-polyaxon-serviceaccount
                     app.kubernetes.io/part-of=polyaxon-core
                     app.kubernetes.io/version=0.6.0
                     chart=polyaxon-0.6.0
                     heritage=Helm
                     release=polyaxon
                     role=polyaxon-config
                     type=polyaxon-core
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   polyaxon-polyaxon-serviceaccount-token-8k4tv
Tokens:              polyaxon-polyaxon-serviceaccount-token-8k4tv
Events:              <none>


Name:                polyaxon-polyaxon-workers-serviceaccount
Namespace:           polyaxon
Labels:              app=polyaxon-polyaxon-workers-serviceaccount
                     app.kubernetes.io/component=polyaxon-config
                     app.kubernetes.io/instance=polyaxon-0.6.0
                     app.kubernetes.io/managed-by=helm
                     app.kubernetes.io/name=polyaxon-polyaxon-workers-serviceaccount
                     app.kubernetes.io/part-of=polyaxon-core
                     app.kubernetes.io/version=0.6.0
                     chart=polyaxon-0.6.0
                     heritage=Helm
                     release=polyaxon
                     role=polyaxon-config
                     type=polyaxon-core
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   polyaxon-polyaxon-workers-serviceaccount-token-78jn8
Tokens:              polyaxon-polyaxon-workers-serviceaccount-token-78jn8
Events:              <none>


Name:                polyaxon-rabbitmq-ha
Namespace:           polyaxon
Labels:              app=rabbitmq-ha
                     chart=rabbitmq-ha-1.38.2
                     heritage=Helm
                     release=polyaxon
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   polyaxon-rabbitmq-ha-token-8m2ts
Tokens:              polyaxon-rabbitmq-ha-token-8m2ts
Events:              <none>
```

**Comment by L-GCHQ** [comment] 2020-02-13 13:08
Having started from a completely fresh install, we have not managed to reproduce this error. The only reason we can think of for this is that something was done out of order the first time round as we were learning how to set things up that were then done correctly later. All the yaml files were the same both times round.

Thanks for your help with this.

**Comment by mouradmourafiq** [comment] 2020-02-13 13:12
Since it's minikube related, I assume that the comment about the hard reset is probably valid. I had issues in the past where I had to hard reset minikube in order to use new flags.

Glad it worked for you.

**Comment by mouradmourafiq** [comment] 2020-03-04 22:31
Closing this issue.

**Closed by mouradmourafiq** 2020-03-04 22:31 UTC
Labels: question
