### ISSUE TITLE
Disable pagination of logs viewer

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#1255] opened 2021-03-30 20:17 UTC
### Current behavior

Currently the logs UI paginates the logs to 50 lines per page, with the option to extend it to 200 line (although this selection is not persisted across different jobs). This pagination makes it hard to efficiently skim the process of jobs. Using inverse sorting is often also not an options since it leads to problems when viewing ANSI tables or any kind of structured console output.

### Enhancement

In general logs usually have many line (especially when installing pip packages or using TensorFlow). Therefore, most log viewers like GitHub actions, GCP or Elastic implement this as an infinitely scrolling list to enable users to quickly skim logs.
I think it would be great if Polyaxon would do the same and ideally also have the option to follow logs so that the newest line will stay in focus.

I think Elastic UI should support virtualization to make the infinite table efficient, but if not this could be implemented with something like https://github.com/bvaughn/react-virtualized.

**Comment by mouradmourafiq** [comment] 2021-03-30 20:54
Virtualization is now supported in the component that we use for the logs and jobs' table, but the PR is still on our end is on hold because there are a couple of regressions in the library, some of the features also that we built need to be updated to work correctly with the virualization, and there are a couple of styling issues as well.

We plan to have those changes fixed by next release v1.8. We will be allowing large page selection for both tables after that.
During the streaming phase, we fetch the last 2000 log lines by default so we might show them at once.

> Using inverse sorting is often also not an options since it leads to problems when viewing ANSI tables or any kind of structured console output.

Ah makes sense :)

**Closed** 2021-07-21 13:10 UTC
Labels: area/ui, enhancement, fixed, roadmap
