### ISSUE TITLE
polyaxon on kubernates created with Kube spray polyaxon-redis is always pending and cluster info has no nodes

### ISSUE THREAD

**Issue by aruninnanje** [polyaxon/polyaxon#539] opened 2019-07-31 15:21 UTC
### Describe the bug
I am trying to install polyaxon 0.5.4 on a kubernetes cluster created kubespray

Issue 1:
The polyaxon installation goes through fine but polyaxon-redis master and slave are in pending state
NAME                                            READY   STATUS    RESTARTS   AGE
polyaxon-docker-registry-86b99bbcfd-8zzft       1/1     Running   0          15h
polyaxon-polyaxon-api-7cc8b545d4-rbn6j          2/2     Running   0          15h
polyaxon-polyaxon-beat-55c8789fc4-9m94p         2/2     Running   0          15h
polyaxon-polyaxon-events-5d979db778-x27s8       1/1     Running   0          15h
polyaxon-polyaxon-hpsearch-86785d7644-5cm69     1/1     Running   0          15h
polyaxon-polyaxon-k8s-events-64cf866dbd-w4crm   1/1     Running   0          15h
polyaxon-polyaxon-monitors-5f7946c668-bb72h     1/1     Running   0          15h
polyaxon-polyaxon-resources-564tm               1/1     Running   3          15h
polyaxon-polyaxon-resources-tjblr               1/1     Running   1          15h
polyaxon-polyaxon-scheduler-56b4cf8cf5-hcft2    1/1     Running   0          15h
polyaxon-postgresql-f7c54b4c4-wkjpz             1/1     Running   0          15h
polyaxon-rabbitmq-ha-0                          1/1     Running   0          15h
polyaxon-redis-master-0                         0/1     Pending   0          15h
polyaxon-redis-slave-0                          0/1     Pending   0          15h

I am able to login into the  api server with default user account  and  When i run cluster info there are no nodes in the cluster
Setting OrderedDict([('check_count', 4), ('current_version', u'0.5.4'), ('min_version', u'0.5.0'), ('log_handler', OrderedDict([('dsn', u'aHR0cHM6Ly84MTc4MjEwYjY4NDU0OGE1Yjk2YjgxMzFmYTY0NWM5ZTozY2IwZGI1OTY5NDU0NjNkYTUzMmUzNmRiZTQ4NjFmNUBzZW50cnkuaW8vMTE5NzQxNg=='), ('environment', u'production'), ('tags', {u'chart_version': u'0.5.4', u'platform_min_version': u'0.5.0', u'cli_latest_version': u'0.5.4', u'cli_min_version': u'0.5.0', u'platform_latest_version': u'0.5.4'})]))]) in the file .polyaxoncli
Starting request to url: http://10.10.0.103:31811/api/v1/versions/cli/ with params: None, data: None
Starting new HTTP connection (1): 10.10.0.103:31811
http://10.10.0.103:31811 "GET /api/v1/versions/cli/ HTTP/1.1" 200 None
Response Content: {"latest_version":"0.5.4","min_version":"0.5.0"}, Headers: {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Origin', 'Server': 'nginx/1.10.3', 'Connection': 'keep-alive', 'Allow': 'GET, HEAD, OPTIONS', 'Date': 'Wed, 31 Jul 2019 15:12:40 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json'}
Setting OrderedDict([('check_count', 4), ('current_version', u'0.5.4'), ('min_version', u'0.5.0'), ('log_handler', OrderedDict([('dsn', u'aHR0cHM6Ly84MTc4MjEwYjY4NDU0OGE1Yjk2YjgxMzFmYTY0NWM5ZTozY2IwZGI1OTY5NDU0NjNkYTUzMmUzNmRiZTQ4NjFmNUBzZW50cnkuaW8vMTE5NzQxNg=='), ('environment', u'production'), ('tags', {u'chart_version': u'0.5.4', u'platform_min_version': u'0.5.0', u'cli_latest_version': u'0.5.4', u'cli_min_version': u'0.5.0', u'platform_latest_version': u'0.5.4'})]))]) in the file .polyaxoncli
Starting request to url: http://10.10.0.103:31811/api/v1/cluster/ with params: None, data: None
Starting new HTTP connection (1): 10.10.0.103:31811
http://10.10.0.103:31811 "GET /api/v1/cluster/ HTTP/1.1" 200 None
Response Content: {"uuid":"2ed8771d97c6483b9805a585e7b19962","version_api":{"major":"1","minor":"14","compiler":"gc","platform":"linux/amd64","build_date":"2019-05-16T16:14:56Z","git_commit":"66049e3b21efe110454d67df4fa62b08ea79a19b","go_version":"go1.12.5","git_version":"v1.14.2","git_tree_state":"clean"},"created_at":"2019-07-30T23:07:30.721584Z","updated_at":"2019-07-30T23:10:48.287679Z","nodes":[]}, Headers: {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Vary': 'Origin', 'Server': 'nginx/1.10.3', 'Connection': 'keep-alive', 'Allow': 'GET, HEAD, OPTIONS', 'Date': 'Wed, 31 Jul 2019 15:12:40 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json'}

Cluster info:

--------------  ----------------------------------------
build_date      2019-05-16T16:14:56Z
major           1
go_version      go1.12.5
git_version     v1.14.2
platform        linux/amd64
git_commit      66049e3b21efe110454d67df4fa62b08ea79a19b
git_tree_state  clean
minor           14
compiler        gc
--------------  ----------------------------------------

When i get the logs of individual pods, i see that there are some communication error with the postgres server but all the pods reach running state, i installed a postgres client and run verification and it succeeds in connecting to the server.
 
### To Reproduce

polyaxon config file is as below
```
namespace: polyaxon
rbac:
  enabled: false
ingress:
  enabled: false
serviceType: NodePort
dns:
  backend: "coredns"

persistence:
  logs:
    existingClaim:
    mountPath: /tmp/logs
    hostPath: /mnt/UII_DataShare/polyaxon/logs
  repos:
    existingClaim:
    hostPath: /mnt/UII_DataShare/polyaxon/repo
    mountPath: /tmp/repos
  upload:
    hostPath: /mnt/UII_DataShare/polyaxon/upload
    mountPath: /tmp/upload
  data:
    data:
      hostPath: /mnt/UII_DataShare/polyaxon/data
      mountPath: /tmp/data
  outputs:
    outputs:
      hostPath: /mnt/UII_DataShare/polyaxon/output
      mountPath: /tmp/outputs
```

I have looked into the issues #274 and #349 but the solutions mentioned there did not work for me.

I am struck on this issue for quiet some time, can you pleas help me solve this problem. 

### Environment
kubectl get nodes
NAME        STATUS   ROLES    AGE   VERSION
uiiusls02   Ready    <none>   29d   v1.14.2
uiiusls04   Ready    master   29d   v1.14.2

helm list
NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
polyaxon        1               Tue Jul 30 19:05:27 2019        DEPLOYED        polyaxon-0.5.4                  polyaxon

**Comment by mouradmourafiq** [comment] 2019-08-01 15:56
Hi I think the issue is that stable redis charts creates persistence by default, and in your case maybe the cluster is not able to create PVC or there's no default storage class.

You should check your storage class: `kubectl describe pvc <pvcname> -n <yournamespace>`

make sure that it has a default class, otherwise you might want to look at the redis chart documentation on the [Helm repo](https://github.com/helm/charts/tree/master/stable/redis) to disable the persistence.

**Comment by aruninnanje** [comment] 2019-08-01 19:44
This turned out to the the case, i created a storage class, persistence volume and claims but now i get another error 

MountVolume.MountOptionSupport check failed for volume "pv00001" : Mount options are not supported for this volume type

**Comment by aruninnanje** [comment] 2019-08-01 19:51
I was using wrong mount options,  i am able to move foward now. Will keep you updated if i face other issue

**Comment by mouradmourafiq** [comment] 2019-08-06 15:30
closing the issue for now. Please feel free to open a new issue(s) if you have any problems.

**Closed by mouradmourafiq** 2019-08-06 15:30 UTC
Labels: question
