### ISSUE TITLE
Last experiment metric redefinition

### ISSUE THREAD

**Issue by antifriz** [polyaxon/polyaxon#541] opened 2019-08-01 13:54 UTC
### Feature motivation

It is a common thing to have one job that does the training and the other that does the evaluation on the same step. Currently, the web experiments list will display only the latest reported metric for a given experiment (so if we have a metric key that is being reported only on some steps, we won't see it all the time).

### Feature description

`Experiment.last_metric` then should be the latest value for each metric key when sorted by step count.
I am not sure what to do when no step value is present, possibly treat step=None as step=-1

### Feature implementation

[`scheduler.tasks.experiments.experiments_set_metrics`](https://github.com/polyaxon/polyaxon/blob/d42eedacdde26ea5766c98c4ecfe7ebd84c9c32c/polyaxon/scheduler/tasks/experiments.py#L126)
I think here the implementation should take place

**Comment by mouradmourafiq** [comment] 2019-08-01 14:11
What version are you running? Last_metric used to show a merged last values, this seems to be a bad regression.

**Comment by mouradmourafiq** [comment] 2019-08-01 14:11
I just tried it on last Polyaxon, at least it's in the v0.5.4.

**Comment by antifriz** [comment] 2019-08-01 14:13
> What version are you running? Last_metric used to show a merged last values, this seems to be a bad regression.

`v0.5.2`

**Comment by mouradmourafiq** [comment] 2019-08-01 14:14
Ok I see, it's a regression in the v0.5, the logic there was modified, I will try to publish a fix this week or early next week.

**Comment by mouradmourafiq** [comment] 2019-08-02 11:06
A fix for this regression will be part of today's patch release v0.5.5.

Closing the issue.

**Closed by mouradmourafiq** 2019-08-02 11:06 UTC
Labels: regression
