### ISSUE TITLE
Improve handling of preemption events and machine failures

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#470] opened 2019-05-30 19:59 UTC
### Feature motivation

Deep Learning workloads and many other tasks running on Polyaxon can be effectively checkpointed and resumed at a later stage. This makes them an ideal fit for [preemptible (or spot) VMs](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms) which can result in huge cost savings since many experiments require expensive GPU or TPU resources.
As outlined in #131, Polyaxon can utilize preemptible VMs. Though working with a preemptible Polyaxon GPU clusters is cumbersome and can be really frustrating since it requires a lot of manual intervention. In this issue I'd like to outline a few problems we are facing with our current preemptible Polyaxon setup.
So far I haven't seen any other hosted or open source service that properly supports this. So I think if Polyaxon gets this right, it would be a huge selling point and differentiating factor and would make Polyaxon resilient to node failures too.

#### Automatically resume preempted experiments

It would be extremely helpful if Polyaxon would automatically resume preempted experiment jobs. As requested in #381 a configurable amount of retries would be a nice touch too. This feature doesn't need to be perfect and support zero-downtime failover, even a hacky implementation using a cron job that resumes preempted pods would improve the experience a lot.

#### Add resume button to UI

Currently experiments can only be resumed via the CLI. It would be handy to have this functionality in the UI as well. 

#### Resume experiments in place

Currently when resuming a preempted experiment job, Polyaxon will create a brand new experiment with a new ID. This means that the new experiment will not retain any labels but still writes into the old output directory (which means that it will show up with the wrong ID in TensorBoard). That results into project pages with a huge number of failed experiments. I think it would be a lot cleaner to only resume the experiment job in place and keep the reference to the original experiment ID. This would also make the distinction between restarted and  resumed experiments a lot clearer.

#### Persist logs of preempted experiments

As discovered in #452 Polyaxon currently doesn't persist logs on node preemtion or failure.

### Feature implementation

Automatic resuming could possibly be implemented by using the [Kubernetes Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) which support the use case of restarting pods that are evicted due to node failures (vs container crashs). For this to work properly users might also need to use something like https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/ in order to properly evict pods before the node reboots.
I am not a Kubernetes expert myself, so I am not sure if there are better ways to solve this. I'd be eager to hear if anyone has solved this problem in a different way already. I'd be happy to sponsor work on this issue if someone from the community would be interested in tackling this.

**Comment by mouradmourafiq** [comment] 2019-05-30 20:25
> Automatically resume preempted experiments

This needs a bit of thinking, but the retries feature will be possible once we finish with the v0.5 migration. There will be a higher component "operation" that will allow to set the retries number, exp backoff, execution time, ... These component will either be created independently or part of a pipeline.

> Add resume button to UI

This is easy to add

> Resume experiments in place

That's something we are really thinking about while preserving the activity of previous experiments, but the feedback is helpful.

> Persist logs of preempted experiments

Not sure yet, I know that some teams have configured their clusters to change the behaviour of the preempted instances.

**Comment by lgeiger** [comment] 2019-06-02 17:48
> This needs a bit of thinking, but the retries feature will be possible once we finish with the v0.5 migration. There will be a higher component "operation" that will allow to set the retries number, exp backoff, execution time, ... These component will either be created independently or part of a pipeline.

Awesome, looking forward to 0.5.
If there also would be a possibility to distinguish between failures due to the docker container crashing (because of a bug in the code) and the whole pod being evicted (due to preemption or machine failure), I think this would get us 80% there.

> That's something we are really thinking about while preserving the activity of previous experiments, but the feedback is helpful.

I think, especially with the addition of the retries feature, it would be a lot cleaner if resumes and retries would show up as additional jobs within the same experiment and not create entirely new experiments.w

**Comment by lgeiger** [comment] 2019-06-07 22:32
> This needs a bit of thinking, but the retries feature will be possible once we finish with the v0.5 migration. 

I think this could be handled by utilising Kubernetes Jobs that allow provide an abstraction to describe pods that should run to completion: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

**Comment by lgeiger** [comment] 2019-06-21 12:48
> This needs a bit of thinking, but the retries feature will be possible once we finish with the v0.5 migration.

@mouradmourafiq This might be interesting for inspiration: [Kubeflow Fairing](https://github.com/kubeflow/fairing/blob/master/fairing/deployers/job/job.py) also uses [Kubernetes JobSpec](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) to run their ML jobs.

**Comment by mouradmourafiq** [comment] 2019-06-21 12:50
A PR is already under review for turning pod to job with a new restarts attr on the polyaxonfile.

**Comment by lgeiger** [comment] 2019-06-21 12:57
> A PR is already under review for turning pod to job with a new restarts attr on the polyaxonfile.

That's great news! I'm really looking forward to that and also Polyaxon 0.5. I can't wait to test the release candidate.

**Comment by mouradmourafiq** [comment] 2019-06-21 13:00
Actually the work has been delayed because we were trying to extract the spawners, to make it a standalone repo (declarative and independent of the platform), which will results in more people being able to contribute and test it independently of the platform, but that's big workshop, there's too much integration with the platform, so we will move it to future releases.

**Comment by mouradmourafiq** [comment] 2019-06-29 09:52
FYI: a `max_restarts` property is now integrated, with possibility to set default value for each kind, unfortunately the migration from from pod to job won't make it to next release, the job controller has serveral limitation and needs further work/restructure.

**Comment by lgeiger** [comment] 2019-06-29 10:30
Thanks for the update, the `max_restarts` will be very useful!

This issue is mainly a collection of problems we noticed when running v0.4.4 on preemptible nodes. I am well aware that some of the issues are hard problems to solve that might take a while. Great to hear you're working on it.

**Comment by lgeiger** [comment] 2019-07-08 15:24
> `max_restarts` property is now integrated, with possibility to set default value for each kind

@mouradmourafiq We tried the `max_restarts` property on the Polyaxon 0.5 release, but it still seams that it doesn't properly handle machine failures or machine preemption. Is there anything we are missing here?

**Comment by mouradmourafiq** [comment] 2019-07-08 15:34
@lgeiger it does not handle preemption, that's why I did not close this issue, as I mentioned in an earlier comment, the job PR was not merged, the `pod_restarts` handles other use cases where the pod might fail because of connectivity, a request, ... to handle the preemption either the users will be using the `restry` features in operations when it's GA, or we need to extend the pod_restars with same features as in jobs without limiting the possibility to add extra logic in sidecars and other injected containers.

**Comment by mouradmourafiq** [comment] 2019-07-08 15:48
any chance you would have a code/way to reproduce preemption.

**Comment by lgeiger** [comment] 2019-07-08 16:05
Oh I see, thanks for the clarification.

> any chance you would have a code/way to reproduce preemption.

I think Google recommends stopping or rebooting the VM: https://cloud.google.com/compute/docs/instances/preemptible
If people use something like https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/ to handle node preemption in a GKE cluster, manually killing a Pod may also work.

**Comment by lgeiger** [comment] 2019-10-10 20:17
It looks like the issue was moved to the 0.7 milestone and 0.6 seems to take longer than expected.
@mouradmourafiq Has there been any progress on this in the meantime or is someone else aware of a workaround for the time being?

Polyaxon is a very nice platform that is working really great for rapid experimentation! However this problem can be a real deal breaker when trying to scale Polyaxon to bigger workloads using expensive accelerators.

Is there anything we could do to help getting this issue resolved? We would be also more than happy to fund work on this.

**Comment by mouradmourafiq** [comment] 2019-10-10 23:31
The [new reconciliation](https://github.com/polyaxon/polyaxon-operator/blob/master/controllers/polyaxonjob_controller.go#L101) logic is using a job under the hood, and the api will give the user the choice to do a `restartPolicy` (to restart in same node or not). Unfortunately the open source repo is not updated yet, and it will take more time for the v0.6 release.

**Comment by mouradmourafiq** [comment] 2020-03-09 18:09
Similar to the comment made in #381, a new termination and restart policy is exposed to handle restarts and retries of jobs.

Regarding the logs, Polyaxon implements a finalizers to collect logs, executed automatically for all jobs unless disabled (here)[https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/polyflow/plugins/__init__.py#L29], this forces k8s to execute the finalizers before completely deleting the resource, so I hope that it will solve this issue. Additionally, and as requested in other issues, Polyaxon now resumes jobs in-place, i.e. same run id, it will automatically collect more logs, more outputs, ... under the same instance. And since Polyaxon has now automatic data/artifacts initiliazers it should work with any storage backend.

Closing this issue, please feel free to reopen in the future once you can use the V1.

**Closed by mouradmourafiq** 2020-03-09 18:09 UTC
Labels: enhancement, feature, operator
