### ISSUE TITLE
Private registry configuration

### ISSUE THREAD

**Issue by DXist** [polyaxon/polyaxon#511] opened 2019-07-17 09:56 UTC
### Describe the bug
I configured external private registry to pull base images. I want to use polyaxon internal registry for built container. There are 2 issues:
1. can't set 'Host' field of registry_access to empty value
2. when set 'Host' field value as 'polyaxon-docker-registry:5000' build container tries to use wrong dns server: `ERROR: Get https://polyaxon-docker-registry:5000/v2/: dial tcp: lookup polyaxon-docker-registry on 172.21.0.1:53: no such host`

I can resolve polyaxon-docker-registry service using

kubectl exec polyaxon-rabbitmq-ha-0 -n polyaxon --  sh -c "nc -v  polyaxon-docker-registry 5000"
### To Reproduce

Create registry_access with blank Host field.

### Expected behavior
I am able to push to local registry without workarounds
### Environment
polyaxon version --platform

Current platform version: 0.5.2.

Kubernetes cluster managed by kubespray and configured coredns

**Comment by mouradmourafiq** [comment] 2019-07-17 09:59
do you set a secret on that access, a `Host or Secret is Required.` that the error you should get if you don't provide any.

**Comment by mouradmourafiq** [comment] 2019-07-17 10:05
<img width="600" alt="Screenshot 2019-07-17 at 12 04 33" src="https://user-images.githubusercontent.com/1261626/61367035-1e131b80-a88b-11e9-8272-06d3db702d8d.png">


<img width="1026" alt="Screenshot 2019-07-17 at 12 04 44" src="https://user-images.githubusercontent.com/1261626/61367033-1e131b80-a88b-11e9-8cf6-b05a0b7a6894.png">

**Comment by DXist** [comment] 2019-07-17 10:07
@mouradmourafiq yes, I set secret and mark access as 'Insecure False'

**Comment by mouradmourafiq** [comment] 2019-07-17 10:14
can you please make a screenshot with the error you receive, I cannot reproduce, at least it should create the access.

**Comment by mouradmourafiq** [comment] 2019-07-17 10:16
Ok this happens on `update`, quick workaround, create a new access.

**Comment by DXist** [comment] 2019-07-17 11:02
Yes, create allows to set blank host

**Comment by mouradmourafiq** [comment] 2019-07-17 16:39
A fix for the issue will be part of v0.5.3.

**Closed by mouradmourafiq** 2019-07-17 16:39 UTC
Labels: bug, ui
