### ISSUE TITLE
Failed to complete entire experiment group

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polyaxon#384] opened 2019-02-25 20:50 UTC
### Describe the bug
Created an experiment group to stress my polyaxon deployment a bit and almost all completed correctly but two experiments failed to get a "completed" state.

One got stuck in a "started" state although it seems to have completed correctly. According to the statuses tab it never managed to leave the "starting" state after the "scheduled" state.

The other one failed to start with a strange error.
```
"Failure","message":"pods \"plxjob-master0-6a83acd8af084000b21bf158a7b0aae2\" already exists"
```
Here it is in full.
```
Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/polyaxon_k8s/manager.py", line 154, in create_or_update_pod self.k8s_api.read_namespaced_pod(name, self.namespace) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 18163, in read_namespaced_pod (data) = self.read_namespaced_pod_with_http_info(name, namespace, **kwargs) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 18254, in read_namespaced_pod_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 342, in request headers=headers) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 231, in GET query_params=query_params) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (404) Reason: Not Found HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 25 Feb 2019 16:31:47 GMT', 'Content-Length': '262'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plxjob-master0-6a83acd8af084000b21bf158a7b0aae2\" not found","reason":"NotFound","details":{"name":"plxjob-master0-6a83acd8af084000b21bf158a7b0aae2","kind":"pods"},"code":404} During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/polyaxon/polyaxon/scheduler/experiment_scheduler.py", line 497, in start_experiment response = spawner.start_experiment() File "/polyaxon/polyaxon/scheduler/spawners/experiment_spawner.py", line 315, in start_experiment master_resp = self.create_master() File "/polyaxon/polyaxon/scheduler/spawners/experiment_spawner.py", line 276, in create_master add_service=self.MASTER_SERVICE) File "/polyaxon/polyaxon/scheduler/spawners/experiment_spawner.py", line 206, in _create_job pod_resp, _ = self.create_or_update_pod(name=resource_name, data=pod) File "/usr/local/lib/python3.6/dist-packages/polyaxon_k8s/manager.py", line 166, in create_or_update_pod resp = self.k8s_api.create_namespaced_pod(self.namespace, data) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6057, in create_namespaced_pod (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6142, in create_namespaced_pod_with_http_info collection_formats=collection_formats) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api _return_http_data_only, collection_formats, _preload_content, _request_timeout) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api _request_timeout=_request_timeout) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 364, in request body=body) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST body=body) File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request raise ApiException(http_resp=r) kubernetes.client.rest.ApiException: (409) Reason: Conflict HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 25 Feb 2019 16:31:48 GMT', 'Content-Length': '272'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"plxjob-master0-6a83acd8af084000b21bf158a7b0aae2\" already exists","reason":"AlreadyExists","details":{"name":"plxjob-master0-6a83acd8af084000b21bf158a7b0aae2","kind":"pods"},"code":409} 
```
### To Reproduce
This was the polyaxonfile.yml that I ran.
```yml
---
version: 1

kind: group

environment:
  resources:
    gpu:
      limits: 1

hptuning:
  concurrency: 5
  random_search:
    n_experiments: 50
  matrix:
    sgd_momentum_factor:
      uniform: 0.5:0.9 # Samples from uniform distribution over [low:hight)
    learning_rate:
      linspace: 0.001:0.1:10 # [start, stop, num] steps from start to stop
    train_batch_size:
      values: [64, 128, 256, 512, 1024]

declarations:
  arch: alexnet
  valid_batch_size: 100
  test_batch_size: 100
  workers: 2
  epochs: 5
  sgd_weight_decay: 0.0001
  seed: 1

build:
  image: pytorch/pytorch:1.0-cuda10.0-cudnn7-runtime
  build_steps:
    - pip install -r requirements.txt

run:
  cmd:  python3 main.py --arch={{ arch }} \
                        --batch-size={{ train_batch_size }} \
                        --valid-batch-size={{ valid_batch_size }} \
                        --test-batch-size={{ test_batch_size }} \
                        --workers={{ workers }} \
                        --epochs={{ epochs }} \
                        --learning-rate={{ learning_rate }} \
                        --momentum={{ sgd_momentum_factor }} \
                        --weight-decay={{ sgd_weight_decay }} \
                        --seed={{ seed }}
```

### Expected behavior
All 50 experiments completing successfully. But I am impressed with version 0.4.0 of Polyaxon so far! I just wanted to give a heads up about this strange error.

### Environment
Polyaxon 0.4.0 on Kubernetes 1.11.7 deployed with kubespray. Running 13 nodes in the cluster but in the polyaxon namespace there are two CPU nodes and two GPU nodes (1+4 GPUs in total).

**Comment by mouradmourafiq** [comment] 2019-02-26 17:27
I have seen this, happends due to concurrency, a solution is underwork, did you manage to reproduce it more than once?

**Comment by AntonFriberg** [comment] 2019-02-26 19:00
I have not yet managed to reproduce it but will let you now if I do! Thanks!

**Comment by AntonFriberg** [comment] 2019-02-28 09:03
Created 12 more realistic long running experiments and did not see any strange behavior.

**Comment by mouradmourafiq** [comment] 2019-04-10 17:57
I have been conducting stress tests on large number of experiment groups on 0.4.3 and 0.4.4 with the different algorithms proposed by the platform, and all tests went through.

I am closing this for now, hopefully noone will encounter this issue again.

**Closed by mouradmourafiq** 2019-04-10 17:57 UTC
Labels: bug, core
