### ISSUE TITLE
Sort by metrics doesn't work at polyaxon 0.5.1

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#509] opened 2019-07-16 18:01 UTC
### Describe the bug
I tried to sort by a metrics in a experiment group on the web UI, but it doesn't work. I attached a part of screenshot of it. 
I tried to sort `f1_micro` which is a metric. But those are not sorted as I expected.

![AwesomeScreenshot-Polyaxon-2019-07-16-10-07-39](https://user-images.githubusercontent.com/1523515/61317780-8c3ade00-a7b8-11e9-88d4-db8b8280b272.png)

### To Reproduce
1. Run a experiment group whose experiments log metrics.
2. Go to the page.
3. Sort experiments by a certain metric.

### Expected behavior
Experiments in a experiment groupu should be sorted by a specified key.

### Environment
- polyaxon: 0.5.1

**Comment by mouradmourafiq** [comment] 2019-08-02 11:10
The field was changed to `metrics` but the api was not updated with a proxy to the underlaying db field. Since the API has a backward compatibility with the field `metric` as well, tests were passing  but the actual logic would only proxy `metric` and not `metrics`.

This was a regression and tests were only updated before for the filtering and not sorting.

The proxy field is added to the sorting logic, and tests are updated to check also for `metrics` as well.

Closing the issue, a fix for this regression will be available for v0.5.5.

**Closed by mouradmourafiq** 2019-08-02 11:10 UTC
Labels: bug, ui

**Comment by Lap1n** [comment] 2019-10-27 21:00
I have the same problem in version 0.5.6
