### ISSUE TITLE
Upgrade to 0.4.4 fails

### ISSUE THREAD

**Issue by CommanderJax** [polyaxon/polyaxon#428] opened 2019-04-10 14:29 UTC
We attempted to upgrade from 0.4.2 to 0.4.4, the upgrade failed due to an error in the ingress TLS section:

`Hi Mourad, we tried upgrading to 0.4.4 and we think there is a regression in ingress object, here is the diff:
```
  # Source: polyaxon/templates/ing.yaml
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: polyaxon-polyaxon-ingress
    namespace: polyaxon
    labels:
-     chart: "polyaxon-0.4.2"
+     chart: "polyaxon-0.4.4"
      release: "polyaxon"
      heritage: "Tiller"
      type: polyaxon-core
      role: polyaxon-api
      app.kubernetes.io/name: polyaxon-polyaxon-ingress
-     app.kubernetes.io/instance: "polyaxon-0.4.2"
-     app.kubernetes.io/version: "0.4.2"
+     app.kubernetes.io/instance: "polyaxon-0.4.4"
+     app.kubernetes.io/version: "0.4.4"
      app.kubernetes.io/part-of: polyaxon-core
      app.kubernetes.io/component: polyaxon-api
      app.kubernetes.io/managed-by: "helm"
    annotations:
-     ingress.kubernetes.io/add-base-url: "true"
-     ingress.kubernetes.io/proxy-body-size: 4G
-     ingress.kubernetes.io/proxy-connect-timeout: "600"
-     ingress.kubernetes.io/proxy-read-timeout: "600"
-     ingress.kubernetes.io/proxy-send-timeout: "600"
-     ingress.kubernetes.io/rewrite-target: /
-     ingress.kubernetes.io/send-timeout: "600"
-     ingress.kubernetes.io/ssl-redirect: "false"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 4G

  spec:
-   tls:
-   - hosts:
-     - polyaxon.domain
-     secretName: star-domain-secret
    rules:
-   - host: polyaxon.domain
+   - host:
      http:
        paths:
        - path: /
          backend:
            serviceName: polyaxon-polyaxon-api
            servicePort: 80
        - path: /ws
          backend:
            serviceName: polyaxon-polyaxon-api
            servicePort: 1337
+   tls:
+
+     enabled: true
+     hosts:
+     - polyaxon.domain
+     secretName: star-domain-secret
```

```
Upgrading polyaxon/polyaxon
2019/04/10 15:18:12 Warning: Merging destination map for chart 'polyaxon'. The destination item 'annotations' is a table and ignoring the source 'annotations' as it has a non-table value of: <nil>
2019/04/10 15:18:12 Warning: Merging destination map for chart 'polyaxon'. The destination item 'tls' is a table and ignoring the source 'tls' as it has a non-table value of: []
UPGRADE FAILED
ROLLING BACK
Error: v1beta1.Ingress.Spec: v1beta1.IngressSpec.TLS: []v1beta1.IngressTLS: decode slice: expect [ or n, but found {, error found in #10 byte of ...|}],"tls":{"enabled":|..., bigger context ...|api","servicePort":1337},"path":"/ws"}]}}],"tls":{"enabled":true,"hosts":["polyaxon.vlt.beno.ai"],"s|...
Error: UPGRADE FAILED: v1beta1.Ingress.Spec: v1beta1.IngressSpec.TLS: []v1beta1.IngressTLS: decode slice: expect [ or n, but found {, error found in #10 byte of ...|}],"tls":{"enabled":|..., bigger context ...|api","servicePort":1337},"path":"/ws"}]}}],"tls":{"enabled":true,"hosts":["polyaxon.vlt.beno.ai"],"s|...

err: release "polyaxon" in "helmfile.yaml" failed: exit status 1
exit status 1
```

From what it looks like - there is an indentation issue problem with the TLS section.

**Comment by mouradmourafiq** [comment] 2019-04-10 14:51
@CommanderJax The ingress resource has changed because we dropped the built-in ingress controller. The new [ingress resource is much simple](https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/templates/ing.yaml) to use, you can check the [values](https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/values.yaml#L7). 

You might need to uncomment the annotations, we commented them to let users decide how they want to set the ingress config.

There's also a guide on how to set the [NGINX ingress](https://docs.polyaxon.com/integrations/nginx/)

Add a mention of this change in the [0.4.3 release](https://github.com/polyaxon/polyaxon/releases/tag/0.4.3) with support of multiple secrets.

**Comment by mouradmourafiq** [comment] 2019-04-10 14:54
so to make it simple your tls config should be :

```
ingress:
  enabled: true
  hostName: polyaxon.acme.com
  tls:
  - secretName: star-domain-secret
    hosts:
      - polyaxon.domain
```

**Comment by mouradmourafiq** [comment] 2019-04-10 15:04
I just tried the snippet above and it works with v0.4.4. Let me know if it solves your issue.

**Comment by mouradmourafiq** [comment] 2019-04-11 07:16
I am closing this, please feel free to reopen, the issue is due to the config file containing pre v0.4.3 ingress definition.

**Closed by mouradmourafiq** 2019-04-11 07:16 UTC

**Comment by CommanderJax** [comment] 2019-04-12 13:02
@mouradmourafiq Sorry for late reply and thanks, it worked!
